### ISSUE TITLE
What is the best way to represent shared fields in Pydantic?

### ISSUE THREAD

**Issue by GlennS** [samuelcolvin/pydantic#1010]
# Question

I quite frequently run into situations where I want to reuse the same field in different models, sharing attributes about them.

What is the recommended approach to do this? I wonder if this might be worth adding something to the documentation about?

I can think of two ways:

## Approach One - Shared a `Field` object between models

I think this is probably the worse choice because it doesn't introduce a #ref for the shared field in the schema, but inlines it. However, it does seem slightly more natural in Pydantic.
```
from pydantic import BaseModel, Field

sharedField = Field("my-default", example="hello I am an example", description="An example field.", nullable=True)

class ModelOne(BaseModel):
    """
    Some documentation about ModelOne
    """
    myField:str = sharedField

class ModelTwo(BaseModel):
    """
    Some documentation about ModelTwo
    """
    myField:str = sharedField
```

## Approach 2 - Create a separate model and assign a different `__root__` type

```
from pydantic import BaseModel, Field

class SharedField(BaseModel):
    """
    Some documentation about SharedField
    """
    __root__: str
    class Config:
        schema_extra = {
            "example": "example of SharedField",
            "nullable": True
        }

class ModelOne(BaseModel):
    """
    Some documentation about ModelOne
    """
    myField:SharedField

class ModelTwo(BaseModel):
    """
    Some documentation about ModelTwo
    """
    myField:SharedField
```

## Background

I currently have an API schema defined using Python dictionaries. I wrote some code to turn those dictionaries into OpenAPI and JSONSchema compatible specs. 

I'm trying to replace some of my code with Pydantic, since I prefer the approach you have taken, and also because it seems quite polished already. Thanks for making it.

# Requested Information
* OS: Linux (Nixos 19.09)
* Python version `import sys; print(sys.version)`: 3.7.5
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 1.0

**Comment by dmontagu** [comment]
There are two other options:

1. Make a custom type. Depending on what you want to do, this may be easier to work with and more performant than using a `__root__` model.

2. Inheritance:

```python
class ModelOne(BaseModel):
    """
    Some documentation about ModelOne
    """
    myField:str = sharedField

class ModelTwo(ModelOne):
    """
    Some documentation about ModelTwo
    """
    # myField already present due to inheritance
    myOtherField: str
```

You can also use a mixin class if that better reflects your data hierarchy:

```
class MyFieldMixin(BaseModel):
    myField: str = sharedField  # defined in your example


class ModelOne(MyFieldMixin):
    """
    Some documentation about ModelOne
    """

class ModelTwo(MyFieldMixin):
    """
    Some documentation about ModelTwo
    """
```

**Comment by samuelcolvin** [comment]
I'd agree with @dmontagu that inheritance was probably the best way.

Let me know if somehow that doesn't work.

**Comment by GlennS** [comment]
Thanks for you help with this guys.

I will try out the mixin approach and see if that works.

**Comment by Fogapod** [comment]
What about more complex types? `__root__` doesn't seem to support `Field`. 
This example produces error for me:
```python
class User(BaseModel):
    nickname: Name

class Name(BaseModel):
    __root__: str = Field(..., regex=r".+")

# AssertionError: Path params must be of one of the supported types
```
I cant use inheritance because I want to use `Name` type separately in a few places in fastapi. 
Am I doing something wrong here?

**Comment by ravwojdyla** [comment]
+1 mixin/inheritance being the best available solution in general, assuming we also care about validators/config etc. That said it's a bit verbose if there's a large number of fields.

If we assume we only want to copy the field (no validators etc), one other option is to dynamically update `__annotations__` + use `Annotated` to capture field info, here's a POC:

```python
from pydantic import Field, BaseModel
from typing import Annotated, Type

def copy_field(from_model: Type[BaseModel], fname: str, annotations: dict[str, ...]):
    annotations[fname] = from_model.__annotations__[fname]

class Foo(BaseModel):
    a: int
    b: Annotated[float, Field(alias="bbb", description="foo desc")]
    
class Bar(BaseModel):
    aa: int
    copy_field(Foo, "b", __annotations__)
    c: float

# notice bbb got copied over:
Bar.schema()
{'title': 'Bar',
 'type': 'object',
 'properties': {'aa': {'title': 'Aa', 'type': 'integer'},
  'bbb': {'title': 'Bbb', 'description': 'foo desc', 'type': 'number'},
  'c': {'title': 'C', 'type': 'number'}},
 'required': ['aa', 'bbb', 'c']}
```

👋 @samuelcolvin is there something obviously wrong with the approach above?

**Comment by dhimmel** [comment]
@ravwojdyla's field copying method using `__annotations__` is handy. Here is the exact same concept, but slightly rewritten and executed in Python 3.13:

```py
from pydantic import Field, BaseModel
from typing import Annotated

class CommonModel(BaseModel):
    b: Annotated[int, Field(description="common field b")]
    c: Annotated[float, Field(description="common field c")]
    
class EndModel(BaseModel):
    a: Annotated[int, Field(description="end model field a")]
    __annotations__["b"] = CommonModel.__annotations__["b"]
    d: Annotated[str, Field(description="end model field d")]

EndModel.model_fields
```

Which outputs:

```py
{'a': FieldInfo(annotation=int, required=True, description='end model field a'),
 'b': FieldInfo(annotation=int, required=True, description='common field b'),
 'd': FieldInfo(annotation=str, required=True, description='end model field d')}
```

In Python 3.14, the `__annotations__` method no longer works due to PEP 649 and PEP 749 deferred evaluation of annotations. You will get:

```
NameError: name '__annotations__' is not defined
```

[`annotationlib.get_annotations`](https://docs.python.org/3/library/annotationlib.html#annotationlib.get_annotations) takes us part of the way there to restoring the copy field method.

Copying fields gives more precise control compared to inheritance. For example, it's nice to copy a subset of a fields or reorder fields (requested in https://github.com/pydantic/pydantic/issues/3838). The order of fields when included by inheritance takes getting used to: fields start with inherited superclasses (reverse order) and then include the fields defined in the current class.

It is nice when each Pydantic model corresponds to one real world dataset. Inheritance forces the user to create models at synthetic levels of abstraction. The alternative and ideal is to copy the field from a model corresponding to the dataset that first created it.

@samuelcolvin any insights on methods that would work with Python 3.14?

**Comment by Viicos** [comment]
Copying from annotations can have several downsides:

- Any `Field()` function assigned to a field (instead of using [the annotated pattern](https://docs.pydantic.dev/latest/concepts/fields/#the-annotated-pattern), i.e. `Annotated[<type>, Field(...)]`) is not going to be picked up.
- This might cause issues with string annotations, that may not resolve properly on the model the annotations are copied over.
- As @dhimmel mentioned, this is not viable approach anymore in Python 3.14.

I think the best way is to use inheritance or simply use a (implicit/explicit) type alias:

```python
from pydantic import Field, BaseModel
from typing import Annotated

B = Annotated[int, Field(description="common field b")]

class CommonModel(BaseModel):
    b: B


class EndModel(BaseModel):
    a: Annotated[int, Field(description="end model field a")]
    b: B
```

If using a [PEP 695 type alias](https://docs.python.org/3/reference/compound_stmts.html#generic-type-aliases), it will appear as a definition in the JSON Schema, but not all `Field()` metadata is being supported (see [docs](https://docs.pydantic.dev/latest/concepts/types/#named-type-aliases)).
