### ISSUE TITLE
Change `make` commands order in Makefile

### ISSUE THREAD

**Issue by MrMrRobat** [samuelcolvin/pydantic#1039]
# Question

Currently calling `make` in project will first run all tests and only after that will run lint checks.
Is there any reason for that?
It doesn't make sense to me as code analysis are complete much faster. Now I have to either run code analyses separately before running make, or wait while all tests will pass.

So can we change this:
```bash
.PHONY: all
all: testcov lint mypy
```
to this:
```
.PHONY: all
all:  lint mypy testcov
```
?

**Comment by samuelcolvin** [comment]
It's a matter of taste, I prefer running tests first.

It didn't make much difference since all parts are pretty far for pydantic.

Happy to change if others also want a change.

**Comment by dmontagu** [comment]
I’m fine either way. I’d say I have a weak preference for the order @MrMrRobat has proposed though.

I frequently find myself hitting a stupid linting issue after running all the tests, then get annoyed because I feel like I should probably make sure everything works after fixing the linting issue by running the tests again. But it’s a pretty minor thing either way.

**Comment by samuelcolvin** [comment]
Okay let's change. PR welcome
