### ISSUE TITLE
Binary protocol parsing/encoding

### ISSUE THREAD

**Issue by aviramha** [samuelcolvin/pydantic#1053]
So I really like pydantic, and in need for a binary encoding/decoding library in Python.
I'm already familiar with construct, but it's usage is not so modern (compared to Pydantic and other modern fancy libraries).

I know pydantic is mostly used for JSON, but have been wondering if there'd been an attempt to use it for binary protocols encoding/decoding? Could it be something that Pydantic would might have in the future?

**Comment by daltonmatos** [comment]
Hello @aviramha, I am also interested in this question. Did you get any response from the project authors?
Do you think pinging them here would be a good idea?

Thanks,

**Comment by samuelcolvin** [comment]
pydantic work with python objects, parsing and validating them.

It's agnostic as to what format the data was in before it was decoded into python (except some utility methods for JSON since it's so common).

Parsing/loading/decoding the data is up to you, you can then pass it to pydantic.

Am I missing something, or misunderstanding your question?

**Comment by daltonmatos** [comment]
Hello @samuelcolvin,

In fact now that you said this I agree that this should not be a responsibility of pydantic.

What I was thinking about was pydantic parsing the raw data based on a declared `BaseModel`, but this would be very complicated to declare, probably because it would be difficult to represent details of the raw data structure only with `Model` fields.

We can leave this issue closed. 😁

Thabks,
