### ISSUE TITLE
The docs use camelCase example, but actually parse PascalCase

### ISSUE THREAD

**Issue by uriva** [samuelcolvin/pydantic#1056]
The docs give this example as a camel case alias generator:

```
def to_camel(string: str) -> str:
    return ''.join(word.capitalize() for word in string.split('_'))
```

But iiuc, this is actually PascalCase. This is a bit confusing, so consider replacing with:

```
def _to_camel(string: Text) -> Text:
    split = string.split('_')
    return split[0]+''.join(word.capitalize() for word in split[1:])
```

Side note: I think camelCase aliasing is common enough to justify its own flag.

**Comment by samuelcolvin** [comment]
From wikipedia:

> Some programming styles prefer camel case with the first letter capitalised, others not.

In other words camel case can mean either `camelCase` or `CamelCase`. I see that pascal case is more specific, but it's also much less well known.

I've added a clarification to the docs.

> I think camelCase aliasing is common enough to justify its own flag.

I'm opposed to adding extra flags to config unless absolutely necessary, especially since:
* config inheritance mean you'd only need to define your alias generator function once
* your issue demonstrates that people might well mean different things by apparently simple terms like "camel case".

**Comment by uriva** [comment]
agree to disagree

imho the vast majority of programmers are interested in what I call camelCase (because they use pydantic for apis, which often enough means javascript with its naming convention, whereas PascalCase is rarely seen in apis these days).

also disliked the "exercice is left to the reader" approach

thanks for clarifying it anyway

**Comment by samuelcolvin** [comment]
If you want to add a brief section to the docs with coffee for the other case, that's fine with me. It was perhaps a little glib to say "go and will it yourself".

**Comment by samuelcolvin** [comment]
> imho the vast majority of programmers are interested in what I call camelCase

I think that's a questionable claim, expecialy since python uses CamelCase.
