### ISSUE TITLE
Model's dict method that contains set of models.

### ISSUE THREAD

**Issue by AlbertMukhammadiev** [samuelcolvin/pydantic#1090]
# Bug

Please complete:
* OS: **19.10**
* Python version `import sys; print(sys.version)`: **3.6.8 [GCC 9.2.1 20191008]**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.2**

I want to create model Foo, that contains collection of Bars:

```py
from typing import Set, Tuple, List
from pydantic import BaseModel


class Bar(BaseModel):
    bar: str = 'bar_value'

    def __hash__(self):
        return self.bar.__hash__()


class FooTuple(BaseModel):
    bars: Tuple[Bar]


class FooSet(BaseModel):
    bars: Set[Bar]


class FooList(BaseModel):
    bars: List[Bar]


if __name__ == '__main__':
    FooList(bars=[Bar()]).dict()
    FooTuple(bars=(Bar(),)).dict()
    FooSet(bars={Bar()}).dict()

...
```

Dict method recursively converts models to dictionaries and tries to put them in the same containers they were in. It falls down for Set because of dict type is unhashable.

**Comment by samuelcolvin** [comment]
Might be possible to fix this but it would take a fundamental change to how models are validated.

I'd be happy to review a PR, but it would need to pass a fairly high bar (no pun intended) of not effecting performance or any backwards incompatibilities.

**Comment by dmontagu** [comment]
Yeah, it's not clear to me what the behavior should be instead; I can't think of a way to change this behavior that wouldn't introduce an inconsistency in the dict-making recursion.

I'd probably recommend overriding `.dict()` on the model that is causing trouble.

If someone has an idea of how this could behave differently (or be easier to override) in a backwards compatible way without just adding another argument to `dict`, I agree that would be interesting.

**Comment by samuelcolvin** [comment]
Okay, I had misread this. The problem is the `.dict()`, not the `FooSet(bars={Bar()})`.

Since I think it's correct that `.dict()` recursively converts sub-models to dictionaries, and it's a limitation of python that 1) items in a set must be hashable, and 2) dicts are not hashable; I don't think this can really be fixed.

The solution is to use `dict(FooSet(bars={Bar()}))` and work from there.

**Comment by DBCerigo** [comment]
We just ran into this same issue, and wanted to share our thoughts (for the core devs and any future finders of this issue). 

1. On a possible general solution:
The issue stems from this line:
https://github.com/samuelcolvin/pydantic/blob/5510a13f6ce2b3909aced8e1ae6a23fea4484862/pydantic/main.py#L598
in
```
class BaseModel(metaclass=ModelMetaclass):
    ...
    def _get_value(
        ...
        elif isinstance(v, (list, set, tuple)):
            return type(v)(
            ...
```
specifically when `v` is a set and that set contains base model(s) which are then exported into a `dict` and thus the unhashable in a set issue arrises.
Our solution to this would be to, in the case in which `v` is an instance of `set`, instead of using `type(v)` instead use `list`, i.e. instead of exporting a set simply export a list. This avoids the need to have hashable items. 
It would create bigger information loss in the export process, and could/would in some cases be a "gotcha" to users in the case that they explicitly needed a set to be returned. But importing that export still works correctly as pydantic will cast that list back into a set. 
At least in our use cases this would have avoided a lot of overhead and "just worked", but of course that's just us specific.

Note also that there is an extra issue when using a `frozenset`. In this case (with `frozenset` not being an instance of `set`) any values of the frozenset (including base models) are passed "as is", without any further export being triggered on them, see; https://github.com/samuelcolvin/pydantic/blob/5510a13f6ce2b3909aced8e1ae6a23fea4484862/pydantic/main.py#L616
Our suggestion would be to remove `set` from the L598 case, and create a new `elif` case which checks for `set` & `frozenset`, which then coerces the export to a list. 

If this seems reasonable to you I can attempt a PR implementing it. (But as you said, this would strictly speaking introduce an inconsistency in the export process (sets being cast to lists).

2. On a workaround:
We did a) add a __hash__ function to our base model to enable it to be an item of a set/frozenset in the first instance, is just uses `hash` on a serialised version of the model (think `dict` then `json.dumps` or something similar).
Then b) we extended `.dict` of our base model to look for the specific attributes that are frozenset/set, and if found then kick off the recursive `dict` sequence on its items;
```
    def dict(self, *args, **kwargs):
        """Converts instance to dict representation of it."""
        d_dict = super().dict(
            *args,
            **kwargs
        )
        if "frozenset_attribute" in d_dict:
            d_dict["frozenset_attribute"] = [x.dict(*args, **kwargs) for x in d_dict["frozenset_attribute"]]

        return d_dict
```
We're not super confident about it yet, but using it for the time being.

**Comment by dmontagu** [comment]
@DBCerigo Thanks for sharing your thoughts!

I see the argument for coercing all sequences to `list`, but this would be a substantial breaking change to the current API, so would probably have to wait for `v2`. Moreover, if you view `dict` as converting things into more of a python-friendly unstructured representation, it feels a little more awkward to convert set to list, so I can see the argument against. But from a practical perspective I think it would be better if this didn't cause errors, so would be fine with creating lists; I'm interested in @samuelcolvin 's opinion here.

@DBCerigo Is there a reason you prefer the approach here over `json.loads(model.json())`? Is performance enough of an issue to merit the added complexity?

I could also be convinced to add a keyword argument to `.dict()` to coerce sequences to list under all circumstances, assuming it had a minimal impact on performance (which I think should be possible). I'm normally averse to adding flags like that, but I think being unable to call `.dict()` on models with a `Set` field is worth handling somehow.

**Comment by samuelcolvin** [comment]
I'm definitely opposed to changing the behaviour to use list instead of set/frozenset. I could perhaps be persuaded of another argument to `.dict()` but I'm not convinced it's necessary.

The fact that `frozenset` is omitted from `(list, set, tuple)` is just a bug and should be fixed.

I think the proper solution here is implement your own logic which iterates through `dict(model)` and builds the object as you need it, perhaps as another method on your own custom base model.

**Comment by DBCerigo** [comment]
Good stuff :) @samuelcolvin appreciate the response and the sentiments - similarly think it is enough of a edge-case and such those people needing that functionality will be able to implement what they need themselves. 

Glad it helped raise a mini bug fix in any case 👍

**Comment by Midnighter** [comment]
I just ran into this problem, too. For me, @DBCerigo 's workaround 2 didn't work. So I came up with this ugly thing that simply converts set attributes to lists first.

```py
    def dict(self, *args, **kwargs):
        """Converts instance to dict representation of it."""
        self.set_attribute = list(self.set_attribute)
        return super().dict(
            *args,
            **kwargs
        )
```

**Comment by chbndrhnns** [comment]
I ran into this today and used @Midnighter 's workaround. When I first hit the issue, I was a bit confused as to what caused it and why exactly this was a problem.

**Comment by iTitus** [comment]
I ran into the same issue. I was trying to use a field of type `set[AnotherModel]` which breaks whenever `._iter(to_dict=True)` is called, for example the `==` operator. Any non-hacky way to fix this?

**Comment by radi-ka** [comment]
I also ran into this and solved the problem with

```python
    def dict(self, *args, **kwargs):
        d = super().dict(
            *args,
            **kwargs
        )

        return frozendict(**d)
```
frozendict: https://pypi.org/project/frozendict/ v2.3.0

**Comment by sasanjac** [comment]
> I ran into the same issue. I was trying to use a field of type `set[AnotherModel]` which breaks whenever `._iter(to_dict=True)` is called, for example the `==` operator. Any non-hacky way to fix this?
> 
> Example:
> 
> ```python
> from pydantic import BaseModel
> 
> 
> class Nested(BaseModel):
>     x: int
> 
>     class Config:
>         frozen = True
> 
> 
> class Model(BaseModel):
>     s: set[Nested]
> 
> 
> x = Model(s={Nested(x=1), Nested(x=2), Nested(x=3)})
> print(x.dict())
> ```
> 
> I would expect the output to be like `{'s': [{'x': 1}, {'x': 2}, {'x': 3}]}`, but I get:
> 
> ```
> Traceback (most recent call last):
>   File "testing.py", line 16, in <module>
>     print(x.dict())
>   File "pydantic\main.py", line 435, in pydantic.main.BaseModel.dict
>   File "pydantic\main.py", line 833, in _iter
>   File "pydantic\main.py", line 759, in pydantic.main.BaseModel._get_value
> TypeError: unhashable type: 'dict'
> ```

Yeah, I don't see how this isn't a bug. It even happens when using `frozenset` instead of `set`.

**Comment by dmontagu** [comment]
I think it might be worth trying to provide a good way to dump a set of frozen models in v2 (whether through a serialization schema or otherwise). I think in v1 though the suggestion in [this comment](https://github.com/pydantic/pydantic/issues/1090#issuecomment-1063984181) above is probably the best way to go.

**Comment by sasanjac** [comment]
> Why would `frozenset` make any difference?

It shouldn't, I was just very confused.

**Comment by markoff-dev** [comment]
I didn’t find anything better for serialization, how to modify @Midnighter proposals
```py
  def json(self, *args, **kwargs):
      """Converts instance to json representation of it."""

      self.set_attribute = list(self.set_attribute)  # noqa
      result = super().json(
          *args,
          **kwargs
      )
      self.set_attribute = set(self.set_attribute)
      return result

  def dict(self, *args, **kwargs):
      """Converts instance to dict representation of it."""

      self.set_attribute = list(self.set_attribute)  # noqa
      result = super().dict(
          *args,
          **kwargs
      )
      self.set_attribute = set(self.set_attribute)
      return result
```

**Comment by lindycoder** [comment]
Also ran in this issue (haven't moved to pydantic 2 yet) described [here](https://github.com/pydantic/pydantic/issues/1090#issuecomment-1013062964) about nested models in a set.

I could solve the issue by using a frozen dataclass.
Limitation: the .dict won't produce dicts, but .json() serializes properly.

```
@dataclass(frozen=True)
class Nested:
    x: int
````

output is `{'s': {Nested(x=1), Nested(x=2), Nested(x=3)}}`

**Comment by lindycoder** [comment]
For pydantic2, this can be solved with a field_serializer
```
from pydantic import BaseModel, ConfigDict, field_serializer


class Nested(BaseModel):
    model_config = ConfigDict(frozen=True)
    x: int


class Parent(BaseModel):
    nested_set: frozenset[Nested]

    @field_serializer("nested_set")
    def serialize_nested_set(self, value: frozenset[Nested]) -> list[Nested]:
        return list(value)


obj = Parent(nested_set=frozenset({Nested(x=1), Nested(x=2)}))
obj.model_dump(mode="python")

```
