### ISSUE TITLE
How to initialise/use validators for ModelField ?

### ISSUE THREAD

**Issue by vitalik** [samuelcolvin/pydantic#1131]
# Question

Please complete:
* OS: **MacOS Catalina**
* Python version : **3.7.4 (default, Nov 12 2019, 15:52:13) [Clang 11.0.0 (clang-1100.0.33.8)]**
* Pydantic version: **1.3**

I'm trying to build some func argument parser/validator and trying to use ModelField directly

example:
```py
from pydantic import Field, BaseConfig
from pydantic.fields import ModelField


f = Field(..., gt=100)  # !!! here I set it to validate for number greater than 100
mf = ModelField(name='myfield', type_=int, class_validators={}, field_info=f, model_config=BaseConfig)

value = mf.validate('1', {}, loc=None)
print(value)

```
but gt=100 validation rule seems not applying 

what's the correct way to do this ? (without using BaseModel)

**Comment by samuelcolvin** [comment]
I think you're going about this the wrong way (see below), but if you really want to do this, have a look at using [`infer`](https://github.com/samuelcolvin/pydantic/blob/e65d11240a6febcd569ad44a61e2374eb00b9ba6/pydantic/fields.py#L246) instead of `__init__`.

---

`ModelField` isn't designed to be used without `BaseModel`, you might get it to work, but it's highly likely it will be broken by a future change we do not consider "breaking" since `ModelField` is not considered part of the public interface. 

For example: we always initialise `ModelField`s via `infer`, so we should probably move that logic into `__init__` and remove `infer`, I wouldn't consider this change to require a major version bump.

Better to use [`parse_obj_as`](https://pydantic-docs.helpmanual.io/usage/models/#parsing-data-into-a-specified-type) or a `BaseModel` directly.

In future pydantic will hopefully add a decorator which validates type hints, see #347. If that's what you're looking for best to upvote or comment there.
