### ISSUE TITLE
Union of Sibling Classes

### ISSUE THREAD

**Issue by aeldaly-tc** [samuelcolvin/pydantic#1218]
How do I use Union properly?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.3
            pydantic compiled: True
                 install path: /usr/local/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Sep 12 2019, 15:40:15)  [GCC 8.3.0]
                     platform: Linux-4.19.76-linuxkit-x86_64-with-debian-10.1
     optional deps. installed: ['typing-extensions', 'email-validator']
```
```py
from typing import Union

from pydantic import BaseModel as PydanticBaseModel


class BaseModel(PydanticBaseModel):
    class Config:
        allow_mutation = False
        case_sensitive = True
        use_enum_values = True
        anystr_strip_whitespace = True


class VendorA(BaseModel):
    name = "VendorA"


class VendorB(BaseModel):
    name = "VendorB"


class VendorTask(BaseModel):
    vendor: Union[VendorA, VendorB]


tasks = [VendorTask(vendor=VendorA()), VendorTask(vendor=VendorB())]

print(tasks)
```

Output is:
`[VendorTask(vendor=VendorA(name='VendorA')), VendorTask(vendor=VendorA(name='VendorB'))]`

What's the best way of achieving the desired result?

**Comment by samuelcolvin** [comment]
This is because `VendorB` as a dict `{'name': 'VendorB'}` is valid as input to `VendorA`.

Solutions:
* use `Literal` on name to force that valid which will allow pydantic to differentiate between an instance of `VendorA` and `VendorB`
* wait for #619 to be implemented, AFAIK no one is working on it though
* perhaps in v2 we'll change how sub-models are parsed, to avoid this problem
