### ISSUE TITLE
Inheritence class defaults are not taken while environment values are processed

### ISSUE THREAD

**Issue by kesavkolla** [samuelcolvin/pydantic#1274]
# Inherited class values are not taken while overriding with environment variables.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.4
            pydantic compiled: True
                 install path: /home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/pydantic
               python version: 3.8.0 (default, Oct 28 2019, 16:14:01)  [GCC 9.2.1 20191008]
                     platform: Linux-5.3.0-40-generic-x86_64-with-glibc2.29
     optional deps. installed: []
```

```py
from pydantic import BaseSettings, Extra, HttpUrl, SecretStr

class AuthSettings(BaseSettings):
    url: HttpUrl = 'https://auth.subsystem.com'
    user: str = 'myuser'
    password: SecretStr = ''

class AppSettings(BaseSettings):
    auth: AuthSettings = AuthSettings()
    db_user: str = 'dbadmin'
    log_level: str = 'INFO'

class IntegrationSettings(AppSettings):
    log_level: str = 'DEBUG'

class ProductionSettings(AppSettings):
    log_level: str = 'WARN'
    auth: AuthSettings = AuthSettings(url = 'https://auth-prod.subsystem.com')
```

I would like to set  the auth password from environment variable so I'm starting python with the following environment variable set.

`export auth='{"password": "prodpassword"}'`

when I create ProductionSettings object I was expecting url would be `auth-prod.subsystem.com` and password woud be `prodpassword`

Whereas pydantic ignoring the url that is given in ProductionSettings class and it's defaulting to the url which is in AuthSettings.

Here is what I'm getting:

```
ProductionSettings(auth=AuthSettings(url=HttpUrl('https://auth.subsystem.com', scheme='https', host='auth-prod.subsystem.com', tld='com', host_type='domain'), user='kesav', password=SecretStr('*****')), db_user='dbadmin', log_level='WARN')
```

**Comment by samuelcolvin** [comment]
The problem is that because there's a value for `auth` when initialising `ProductionSettings` the default value (in this case `AuthSettings(url='https://auth-prod.subsystem.com')`) is being ignored.

I don't really see a work around for this since it's fundamental to how pydantic works.

You could work around this by setting `export password="prodpassword"` which will give you the right result (provided `auth` isn't set) since it'll be considered when `AuthSettings` is initialised while `ProductionSettings` is being defined. But that's ugly, bother because `ProductionSettings` and `AuthSettings` are not initialised at different times, and because properties of `AuthSettings` aren't being read from the correct namespace.

The best option would be something like 

```py
from pydantic import BaseSettings, Extra, HttpUrl, SecretStr
from devtools import debug

class AuthSettings(BaseSettings):
    url: HttpUrl = 'https://auth.subsystem.com'
    user: str = 'myuser'
    password: str = ''

class AppSettings(BaseSettings):
    auth: AuthSettings
    db_user: str = 'dbadmin'
    log_level: str = 'INFO'

class ProdAuthSettings(AuthSettings):
    url: HttpUrl = 'https://auth-prod.subsystem.com'

class ProductionSettings(AppSettings):
    log_level: str = 'WARN'
    auth: ProdAuthSettings = {}

debug(ProductionSettings())
```
(use of `{}` for the default of `auth` prevents an error if auth isn't set and will cause a default `ProdAuthSettings` to be initialised)
