### ISSUE TITLE
Recursive model: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by iamstiil** [samuelcolvin/pydantic#1370]
# Bug

`RecursionError: maximum recursion depth exceeded while calling a Python object`

I get this error message, when using recursive models.

```py
class A(BaseModel):
    ...

class B(A):
    key: List[B]
    ...
```

Using

```py
from __future__ import annotations
from typings import ForwardRef

B = ForwardRef('B')
...
B.update_forward_refs()
```

does not make a difference aswell.

Issue #531 did not have any clue on how to solve this. The docs don't cover the usage with lists. 

Hope you understand my issue here :smile:

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /usr/local/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Feb 26 2020, 14:58:38)  [GCC 8.3.0]
                     platform: Linux-5.3.0-45-generic-x86_64-with-glibc2.2.5
     optional deps. installed: ['email-validator']
```

EDIT:
Just saw that the issue is pointed to in #524, but there is no response. Maybe there is a solution for it now?

**Comment by samuelcolvin** [comment]
I don't think there's currently a solution for this. The most relevant discussion to this is #659, though I wouldn't all this a duplicate since that's specific to `from_orm`.

The short answer is that pydantic doesn't (yet) have any solution for detecting and coping with circular references.

If you have a suggestion of a solution, please comment on #659 or submit a demo PR. I have no idea off the top of my head, how hard it would be to use the same approach for `from_orm`, `parse_obj` and our case above - or if they're even particularly linked.
