### ISSUE TITLE
wrong json() behavior for nested models with __root__

### ISSUE THREAD

**Issue by silversurfer34** [samuelcolvin/pydantic#1414]
hello I have some issues with root

```
class Pets(BaseModel):
    __root__: List[str]
class PetHouse(BaseModel):
    Animals: Pets
    Location: str


pet1 = Pets(__root__=['dog', 'cat'])
pet2 = Pets.parse_obj(['dog', 'cat'])
pet1_json_str = json.dumps(pet1.json())
pet2_json_str = json.dumps(pet2.json())

pet_house_json_str = '{"Animals": ["dog", "cat"], "Location": "Montpellier"}'
pet_house = PetHouse(**json.loads(pet_house_json_str))
pet_house_result_json_str = json.dumps(pet_house.json())

my_pets = pet_house.Animals
my_pets_result_json_str = json.dumps(my_pets.json())

```

we have {"Animals": ["dog", "cat"], "Location": "Montpellier"} as input json
we have {"Animals": {"root": ["dog", "cat"]}, "Location": "Montpellier"} as result json, from the pydantic object which make it impossible to reload by other application

Moreover my_pets_result_json_str gives ["dog", "cat"] ...
(sorry if the format is not correct, it is my first bug on github)

**Comment by samuelcolvin** [comment]
> sorry if the format is not correct, it is my first bug on github

No problem. In future please follow the template you would have seen when you first create the issue  if you'd chosen "bug" or "question" and fill the information it requests.

---

This look like a bug, I haven't seen it before since normally users don't use custom root types except in the root model.

I'll try and fix or or (or PR welcome if you'd like to fix it) but the best work around would be to not use models with custom root types as sub-models

**Comment by silversurfer34** [comment]
Hello again, I propose this PR https://github.com/samuelcolvin/pydantic/pull/1429 to fix this.

To explain why I have nested models with __root__, in fact I am using another project that generates a pydantic model from an openapi definition (https://github.com/koxudaxi/datamodel-code-generator) and this is the output of this generator.
