### ISSUE TITLE
More sophisticated validation for Unions to avoid coercion when not needed

### ISSUE THREAD

**Issue by jvolkman** [samuelcolvin/pydantic#1423]
# Bug

I've run into an issue in which an object's `__field_set__` is fully populated depending on a containing Union's order, despite no fields being set.

The example below defines a `Parent` class and a `Child` subclass. If `Parent()` is set on a `Union[Child, Parent]` field, all of its fields will be listed in `__fields_set__`.

Hopefully the example and output below do a better job of explaining.

```py
from typing import Union
import pydantic


class Parent(pydantic.BaseModel):
    field_that_should_be_unset: str = None


class Child(Parent):
    pass


class Container(pydantic.BaseModel):
    parent_first: Union[Parent, Child] = None
    child_first: Union[Child, Parent] = None


print(
    Container(
        parent_first=Parent(),
        child_first=Parent(),
    ).dict(exclude_unset=True)
)
print(
    Container(
        parent_first=Child(),
        child_first=Child(),
    ).dict(exclude_unset=True)
)
```

Output:
```
{'parent_first': {}, 'child_first': {'field_that_should_be_unset': None}}
{'parent_first': {}, 'child_first': {}}
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /home/jvolkman/repos/tms/env/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Mar 13 2020, 10:14:16)  [GCC 9.3.0]
                     platform: Linux-5.4.0-26-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

and

             pydantic version: 1.5
            pydantic compiled: True
                 install path: /home/jvolkman/repos/tms/env/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Mar 13 2020, 10:14:16)  [GCC 9.3.0]
                     platform: Linux-5.4.0-26-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

```

**Comment by samuelcolvin** [comment]
We might one day have more sophisticated logic to deal with unions, perhaps linked to #619.

Currently there's no work around for this:
* `Parent` is not a subclass of `Child`
* however `Parent` can be coerced to a child via effectively `Child(**parent.dict())`
* doing `Child(**parent.dict())` obviously sets `child. field_that_should_be_unset`, hence the confusing behaviour

**Comment by samuelcolvin** [comment]
We could also solve this (although it would make `Union` slow) by doing two (or even 3) passes through the union options:
1. check if the value is an **exact** instance of the union types: `any(value.__class__ == t for t in union_types)`
2. check if the value is an instance of any subclass of the union types: `any(isinstance(v, t) for t in union_types)`
3. try coercing the value to each type in turn of the union as we do now.

**Comment by yandrieiev** [comment]
I believe that several reported Union-related bugs (or supposed bugs) have wrong emphasis in their descriptions (and some of them are closed now). What is really important about this (and related) issues is that they lead to **surprising silent data-loss**. Each of those adjectives is bad on it's own, but here we have all of them combined. Let me illustrate. The following test case fails on the last assert because last_name was removed by type coercion.

```python
@pytest.mark.xfail(reason='Prioritization results in data loss', raises=AttributeError)
def test_union_priority_data_loss():
    class Person(BaseModel):
        name: str
        last_name: str

    class NamedThing(BaseModel):
        name: str

    class Container(BaseModel):
        v: Union[NamedThing, Person] = ...

    container = Container(v=Person(name='Name', last_name='Last Name'))

    assert container.v.name == 'Name'
    assert container.v.last_name == 'Last Name'
```

In my application code I encountered this like 3 times already for a small-size prototype level app, so this is not a contrived example, but obviously I simplified it.

@samuelcolvin I like your solution you proposed above.

> We could also solve this (although it would make Union slow) by doing two (or even 3) passes through the union options:
>     1. check if the value is an exact instance of the union types: any(value.__class__ == t for t in union_types)
>     2. check if the value is an instance of any subclass of the union types: any(isinstance(v, t) for t in union_types)
>     3. try coercing the value to each type in turn of the union as we do now.

When choosing between surprising silent data-loss and slowing down pydantic in some use-cases where I feel most users won't even notice I would choose slowing down but having a predictable (I would even say correct) behavior. To mitigate slow down for those who care we could add some extra flag into the Field class so that they could keep old behavior until #619 is implemented.

I've read discussion in #619 and I feel that it won't solve this issue because even with implemented discriminator field I feel **it is wrong to force users to use extra (discriminator) field** if they don't want it.

User may also may encounter data-loss (rounding floats) with using simply Union[int, float] and surprising behavior when using Union[float, int] which is functionally equivalent to Union[float]. Yes, user may circumvent these issues with using Union[StrictInt, StrictFloat] but this still feels like a workaround for initially unexpected behavior.

@samuelcolvin what do you think?

**Comment by SaschaSchlemmer** [comment]
@yandrieiev generously sprinkling 

```python
class Config:
    extra = 'forbid'
```
over all your models solves that issue:

```python
class Person(BaseModel):
        name: str
        last_name: str

class NamedThing(BaseModel):
        name: str
            
        class Config:
            extra = 'forbid'

class Container(BaseModel):
        v: Union[NamedThing, Person] = ...
```

**Comment by samuelcolvin** [comment]
I'm as big a fan of generous sprinkling as the next man, but you can accomplish the same thing with a custom base model which is slightly more succinct.

**Comment by vincentsarago** [comment]
👋 First @samuelcolvin and all other contributors thanks for this awesome library 🙏. 

I'm not sure if this is the best place to share but we recently encountered a really strange bug with Union

```python
from typing import Tuple, Union
from pydantic import BaseModel

NumType = Union[float, int]

def f(input: Tuple[Union[int, float], Union[int, float]]):
    pass

class myModel(BaseModel):
    coordinates: Tuple[NumType, NumType]

myModel(**{"coordinates": (0.0, 0.1)})

#>> myModel(coordinates=(0, 0))
```

In☝️there seems to be a conflict with the Type passed in the function (f) `Tuple[Union[int, float], Union[int, float]]` and the `NumType` we use in our Model `myModel`. When declaring the function f, the model will return `int` while we are expecting `float`. If we remove the function f, the model behaves as expected.

I'm happy to open a new issue if you feel this is unrelated to this one 

cc @geospatial-jeff @drewbo
