### ISSUE TITLE
State changes of a nested object after initialization of a main object 

### ISSUE THREAD

**Issue by nikolay-sokolov-qs** [samuelcolvin/pydantic#1434]
# I can't have ability to change the state object. This is a bug or feature?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
        pydantic version: 1.5
       pydantic compiled: False
            install path: /home/user/PycharmProjects/****/venv/lib/python3.6/site-packages/pydantic
          python version: 3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]
                platform: Linux-5.3.0-7648-generic-x86_64-with-Ubuntu-18.04-bionic
optional deps. installed: []

...
```

```py
from pydantic import BaseModel

class Car(BaseModel):
     color = 'blue'
   
class Person(BaseModel):
     car: Car = None
     
>>> car = Car()
>>> person = Person(car=car)
>>> car is person.car
False


# I would like to have an ability to change the state of the field such way
>>> car.color = 'black'
>>> person.car.color  # I would like to get 'black'
'blue'
```

**Comment by StephenBrown2** [comment]
To change the state of the field in the Person model, you would simply need to modify that value:
```py
>>> person.car.color = 'black'
>>> person
Person(car=Car(color='black'))
```
rather than the one outside of/unrelated to the one passed to `person`.

**Comment by nikolay-sokolov-qs** [comment]
@StephenBrown2 Yes, this obviously works, but it would be more convenient to be able to change the state of the `Car` instance (as I wrote above). For example, Django allows you to use this way.

**Comment by StephenBrown2** [comment]
@nikolay-sokolov-qs Personally I'm not in favor of that way, it seems risky to me to be able to modify an unrelated instance and have other models affected, so I guess I won't be using Django. @samuelcolvin should have the final say on if pydantic should allow values by reference, though.

**Comment by samuelcolvin** [comment]
The fix would be very simple, it would be as simple as changing

https://github.com/samuelcolvin/pydantic/blob/881df8bde7bfc90e3a349c420d0b0b7d46237d59/pydantic/main.py#L575

You could even do this on your own custom base model.

The problem is that when you create a model by parsing input data everything get's copied - mostly that's correct since input data can be mutated to match the model and it would be weird in the raw input object was changed by that.

I think it would be too confusing to break that rule here.
