### ISSUE TITLE
how does pydantic differ from attrs? what needs does it fulfil that attrs does not address?

### ISSUE THREAD

**Issue by simkimsia** [samuelcolvin/pydantic#1459]
# Question

Apologies if this is the wrong place to ask this question. 

I am trying to apply DDD design in my Django apps.

So from there I discover attrs and dataclasses. This article https://www.revsys.com/tidbits/dataclasses-and-attrs-when-and-why/ helped me greatly understand their differences

I stumble upon pydantic so I have tried googling but still none the wiser what pydantic helps to solve that attrs does not. 

I think the only one I can find is the typehinting in the IDE. I want to learn so I am posting this question.

Thank you

**Comment by samuelcolvin** [comment]
**(I haven't used attrs extensively, so this may be wrong. Anyone with more experience of attrs, feel free to correct me or add to my answer)**

The only direct comparison I know is between the attr definition in benchmarks and pydantic definition: [pydantic benchmarks model definition](https://github.com/samuelcolvin/pydantic/blob/881df8bde7bfc90e3a349c420d0b0b7d46237d59/benchmarks/test_pydantic.py#L12-L41) vs [attr benchmarks model definition](https://github.com/samuelcolvin/pydantic/blob/881df8bde7bfc90e3a349c420d0b0b7d46237d59/benchmarks/test_cattrs.py#L14-L91).

The problem is that attr lacks many of the validation tools of pydantic, so even for the benchmark we had to use attr + cattr.

---

Basically attr is much lower level and leaves most validation up to you, it doesn't use or respect type annotations and it lacks many features of pydantic like:
* [schema generation](https://pydantic-docs.helpmanual.io/usage/schema/)
* automatic parsing and validation for many standard library types, see [here](https://pydantic-docs.helpmanual.io/usage/types/#standard-library-types)
* custom types, see [here](https://pydantic-docs.helpmanual.io/usage/types/#pydantic-types)
* [json serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeljson)
* [dataclasses integration](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
* the [validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)

attr is fast though, in some cases even faster than pydantic i think.

**Comment by simkimsia** [comment]
Thanks for the reply. I will take some time to go thru this and if I have more questions, will update

**Comment by kolypto** [comment]
The number one feature that is missing, in my opinion, is error path: attrs tells you that you have a validation error, but it does not tell you where. If this data is send to some UI, they won't know which fields to highlight :)
