### ISSUE TITLE
Use self in validators

### ISSUE THREAD

**Issue by 3b4mb4** [samuelcolvin/pydantic#1521]
# Question

I need to initialize field with private attribute, but it isn't listed in values and not accessible cause validators use `cls` and not `self`.

What i want:
```py
from pydantic import BaseModel, validator
from typing import List

class Beer(BaseModel):
    __slots__ = ("_thing",)
    _thing: int

    other_data: str

    def __init__(self, thing: int, **kwargs):
        object.__setattr__(self, "_thing", thing)
        super().__init__(**kwargs)


class User(BaseModel):
    __slots__ = ("_thing",)
    _thing: int

    beers: List[Beer]
    other_data: str

    def __init__(self, thing: int, **kwargs):
        object.__setattr__(self, "_thing", thing)
        super().__init__(**kwargs)

    @validator("beers", pre=True, each_item=True)
    def beers(cls, v: dict, values: dict) -> Beer:
        return Beer(values["_thing"], **v)
    # or
    @validator("beers", pre=True, each_item=True)
    def beers(self, v: dict, values: dict) -> Beer:
        return Beer(self._thing, **v)
```

**Comment by samuelcolvin** [comment]
Unfortunately this isn't currently possible. The reason validators have to be class methods is because the `validate_model` method (which does the meat of validation) has no access to the model instance.

You should use your approach in the first "beers" method above. If that doesn't work, this might be fixed better with "computed fields" broadly described in https://github.com/samuelcolvin/pydantic/issues/935#issuecomment-555036039

**Comment by 3b4mb4** [comment]
Ok, I can't use self in validators, but how I can transfer private attribute to model fields? Examples which i gave isn't working, it's here just to show what I want to do.
