### ISSUE TITLE
Unexpected behavior when using `validate` classmethod together with construct

### ISSUE THREAD

**Issue by argaen** [samuelcolvin/pydantic#1546]
# Bug

Hello! sorry if this is not a bug and it is expected behavior but as user I found it unexpected. I want to be able to create an instance that could potentially host invalid data, for that I can use `construct`. However, later I want to validate that the data inside that class is valid. For that, I was trying to use `Model.validate(qwe)`. However this doesn't work and just returns a copy of the class, checking the behavior, seems it is what it literally does in https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L577. Why would a validate method just return a copy of the object that gets passed? What's the use case for that behavior? I would have expected that it would do something like `return validate_model(cls, value.dict())` for example?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /home/blck/.pyenv/versions/3.8.1/envs/aiocache38/lib/python3.8/site-packages/pydantic
               python version: 3.8.1 (default, Feb  4 2020, 23:35:27)  [GCC 7.4.0]
                     platform: Linux-5.4.0-26-generic-x86_64-with-glibc2.27
     optional deps. installed: []
```

```py
from pydantic import BaseModel

class Model(BaseModel):
    a: int
    b: int

qwe = Model.construct(a=1)

Model.validate(qwe) # Doesn't fail  
Model.validate(qwe.dict())  # fails
```

I would happy to provide a PR fixing this if you also believe the behavior when passed an instance of a class should be calling `validate_model`

**Comment by samuelcolvin** [comment]
`validate()` is not documented, it should have been private, but now it's widely used I can't just make it private. I'll try and sort this in v2, hopefully with a deprecation warning.

`validate()` is used when validating sub-models recursively. pydantic always makes a new copy of the data it's validating, rather than modifying it's input, right or wrong that's assumed behaviour by a lot of code so can't change now. `validate()` follows that principle.
