### ISSUE TITLE
Nested models returning values empty when invalid

### ISSUE THREAD

**Issue by fsramalho** [samuelcolvin/pydantic#1643]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /Users/fabioramalho/CODING/open-source/pydantic/pydantic
               python version: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
                     platform: Darwin-19.5.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator', 'devtools']

```

```py
from pydantic import BaseModel, root_validator

class Bar(BaseModel):
    field_1: str
    field_2: str

    @root_validator
    def check_fields_are_equal(cls, values):
        if values.get("field_1") == values.get("field_2"):
            raise ValueError("`field_1` cannot be the same value as `field_2")
        return values

class Foo(BaseModel):
    bar: Bar
    number: int

    @root_validator
    def number_1_not_field_1_a(cls, values):
        number = values.get("number")
        bar = values.get("bar")

        if number == 1 and if bar and bar.field_1 == "a":
            raise ValueError("It is invalid `number` = 1 and `bar.field_1` = a")

        return values

Foo.validate(dict(number=1, bar=dict(field_1="a", field_2="a")))
```
Running the code above we get only one error
```
1 validation error for Foo
bar -> __root__
  `field_1` cannot be the same value as `field_2 (type=value_error)
```

However I would be expect this
```
2 validation errors for Foo
bar -> __root__
  `field_1` cannot be the same value as `field_2 (type=value_error)
__root__
  It is invalid `number` = 1 and `bar.field_1` = a (type=value_error)
```
 as the root validator `number_1_not_field_1_a` condition is true.

I was looking into the code and found the logic behind that behaviour
https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L899

which seems the value will be only assigned to the field if there are no errors. In my point of view, it would not be harmful if the value is always assigned to the field since if there are errors they will be always raised, so the data will never be valid.

@samuelcolvin I am keen to know your thoughts on this and I am happy to raise a PR with the small change in the `validate_model` function + tests 😃

**Comment by samuelcolvin** [comment]
This is how pydantic has always been, my concerns are:
1. This would likely break a lot of code in many subtle ways - If we do make a change it would need to happen in v2
2. There's no obvious choice for what value a field should have if validation fails - we could take the original value (which might not exist as it might have been muted) or the value as it was just before an error occurred which could be very confusing.

To explain problem 2. further, take this example:

```py
from pydantic import BaseModel, validator

class UserModel(BaseModel):
    foo: str
    bar: str

    @validator('bar')
    def passwords_match(cls, v, values, **kwargs):
        if 'foo' in values and values['foo'].startswith(v):
            raise ValueError('foo does not start with bar')
        return v

UserModel(foo={'this is not': 'a string'}, bar='xxx')
```

Currently it's fine because `foo` is missing from `values`, but if we implemented your change, we could make no assumptions about the type of `values['foo']` and would have to always check it every validator.

I think since there's no sensible way of working around this, omitting `'foo'` from `values` makes the most sense.
