### ISSUE TITLE
min_size, max_size, lt, gt - what to do 

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#174]
from @Gr1N on #171

> I would like to rename `gt` and `lt` in `ConstrainedInt` and `ConstrainedFloat` because we already have `min_number_size` and `max_number_size` for `int` and `float` and to my mind it looks like kind of inconsistency. And I think we can do this backward compatible by adding new `min_size` and `max_size` without removing `gt` and `lt`. What do you think?

We had a discussion and I said I'd do a PR, however having through about it I have the following concerns:
* why would anyone ever want to constrain all numbers to a given range? It sounds like a very unlikely thing to want to do IRL. It's obvious that people want to constrain **some** numbers, but **all** by default? That sounds weird. This was a mistake of mine right at the beginning.
* there are definitely problems with `max_size` vs. `lt`:
  * different names is confusing
  * as discussed on #171 they mean different things: specifically "max size" is really closer to "less than or equal to"
* `lt` and `gt` are useful because they can be used to implement `PostiveXXX` and `NegativeXXX` in a canonical way: AFAIK `PostiveInt` should be `> 0` but not `0`.
* `max_size` is a dumb and verbose name, `max` would be sufficient but

My proposal: get rid of `max_number_size` and `min_number_size` from `Config` completely and leave range constraints to `constr` and `confloat`.

@Gr1N do you agree with this?

**Comment by Gr1N** [comment]
Sounds great! Also I have same feeling about `anystr` related properties in `Config`. Can we remove them too?

One more reason why I like you idea is because we can simply validators by removing `getattr` in prior of using just `field.type_.min`.

And one more moment about renaming, maybe better to use `minimum` and `maximum` because in Python we have `min` and `max` builtin functions.

**Comment by Gr1N** [comment]
@samuelcolvin any progress? If you have no time I can help you.

**Comment by samuelcolvin** [comment]
I think this can be closed, but happy to discuss more if anyone is unclear.

**Comment by jaheba** [comment]
Just to chime in on the discussion.

`gt` and `lt` are horrible names, since they imply that the comparisons used are `>` and `<`. In Python these two names have a distinct meaning (see the [operator module](https://docs.python.org/3/library/operator.html) as an example). `ge` (greater equal) and `le` (less equal) would be the right name in that case.

I actually was thrown off, when I read the documentation / code.

When I read this

```py 
class PositiveInt(ConstrainedInt):
    gt = 0

# or 
big_int: conint(gt=0)
```

I would assume that all values which are at least one are valid, but the lower bound is actually 0.

Thus, I would propose to use `min_value` and `max_value`, a convention [other](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.integers) libraries have chosen.

**Comment by samuelcolvin** [comment]
@jaheba, the problem is not with the names, but with the code, this was fixed in #188.

`gt` and `lt` are used specifically because they imply `>` and `<` respectively. That's what's implemented on master and will be released soon:

```py
 class Foo(BaseModel):
     big_int: conint(gt=0)
     
 Foo(big_int=0)
#> validation error
Foo(big_int=0)
#> <Foo big_int=1>
```

This `big_int` has to be **greater than** `0`.

This was done to allow `PositiveInt` to behave correctly.

We could also allow `ge` or `le` but I think that's unnecessarily complicated.

**Comment by jaheba** [comment]
Sorry for being so brush in my first comment.

I think fundamentally, the issue is that there are cases where you want either behaviour.

Say, I want a float value in the range of `[0, 1]`, that is `0 <= x <= 1`. In this case, I can't use `confloat`, since it's semantic will exclude `0` and `1` from the set of allowed values. And since I use floats, I can't use any other value to make it work.

Thus, the range `(0, 1)` (`0 < x < 1`) works, but we would have the same issue with the old behaviour.

Although it might complicate things, I would advocate for supporting all four operators (ge, gt, le, lt):

```py
def number_size_validator(v, field, config, **kwargs):
    assert not (field.type_.gt is not None and field.type_.ge is not None),\
        'ge and gt can't be specified at the same time'

    assert not (field.type_.lt is not None and field.type_.le is not None),\
        'le and lt can't be specified at the same time'

    if field.type_.gt is not None and v < field.type_.gt:
        raise errors.NumberGtError(limit_value=field.type_.gt)
    elif field.type_.ge is not None and v <= field.type_.ge:
        raise errors.NumberGtError(limit_value=field.type_.ge)
   ...

    return v
```

**Comment by jaheba** [comment]
Can do :)

My current idea is be to create a metaclass for checking for conflicts:

```py

class ConstrainedMeta(type):
    def __new__(cls, name, bases, dct):
        new_cls = type.__new__(cls, name, bases, dct)
        assert new_cls.gt is None or new_cls.ge is None
        assert new_cls.lt is None or new_cls.le is None
        return new_cls


class ConstrainedInt(int, metaclass=ConstrainedMeta):
    gt: Optional[int] = None
    ge: Optional[int] = None
    lt: Optional[int] = None
    le: Optional[int] = None
    
    ...
```

This essentially ensures that only one of the comparison fields is set during class creation.

**Comment by samuelcolvin** [comment]
Looks good except we will need informative exceptions, and best to raise `ConfigError`

**Comment by jaheba** [comment]
Right, just wanted to check that you would agree with the general approach.
