### ISSUE TITLE
Conditional load relationship on from_orm

### ISSUE THREAD

**Issue by teamhide** [samuelcolvin/pydantic#1806]
For example, we have sqlalchemy models post and comment.

```
class Post(Base):
    __tablename__ = 'post'

    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(Unicode(255), nullable=False)

    comments = relationship('Comment')


class Comment(Base):
    __tablename__ = 'comment'

    id = Column(Integer, primary_key=True, autoincrement=True)
    body = Column(Unicode(255))
    post_id = Column(ForeignKey('post.id'))
```

And also have two pydantic models.

```
class CommentModel(BaseModel):
    id: int
    body: str

    class Config:
        orm_mode = True


class PostModel(BaseModel):
    id: int
    title: str
    comments: List[CommentModel]

    class Config:
        orm_mode = True
```

When we load `Post` from `PostModel` via `PostModel.from_orm(post)`, all `comments` related to `Post` loaded eager.

I know that we can avoid it through make another model exclude comments.

```
class PostExcludeCommentModel(BaseModel):
    id: int
    title: str

    class Config:
        orm_mode = True
```

But it is not elegant and we have to check it if comments is need or not in code.

Is there any option for lazy loading on BaseModel?

Thanks.

**Comment by ajgrover** [comment]
This is related to #659. I'm in a situation where the same issue would be very useful, not strictly because of circular references, but because it doesn't always make sense to serialize every related model recursively.

You may want to load a Post and the related Comments, but you don't want the Author and the author's Posts for every single comment (and so on). There's currently no way to support that, if you call `from_orm` on an object you're forced to get every related object defined in your pydantic models, which may either be recursive or a huge number of objects.

Creating subclasses of each pydantic model doesn't seem like a realistic solution. If you have an ORM object with a lot of foreign keys, you may need to have a subclass for every single permutation of those keys. It would make a lot more sense IMO to do something like `include/exclude=['field_name']` similar to the proposals in #830/#959.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
