### ISSUE TITLE
🙏 Sorry, I'm really busy at the moment

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#1913]
Hi, you might have noticed that support on pydantic and particularly reviewing and merging pull requests is a bit slow at the moment. 

@PrettyWood and others have been amazing in their support recently, but I have been noticeably absent, and I know that slows things down or stops them.

**I'm really sorry about that**, I'm currently flat out with work at my new role with Nell Health and have reduced time to spend on pydantic.

I'm still committed to pydantic, I use it most days, I rely on it in production with multiple projects. I want the new features currently languishing in PRs and issue descriptions as much as you. I also have big ideas about v2 and how we can make pydantic both faster and easier to use at the same time.

**I'll do my best to review all open pull requests and issues over the month**.

## You can help!

If you're waiting on new features, please consider helping out with the pydantic project, you could:
* check open issues you've created, check if they're still relevant and either add more information or close them
* look through recent open issues and see if you can solve their problem, give feedback on a feature request or confirm a bug
* review, try and give feedback on open pull requests

**Comment by xkortex** [comment]
I **really** appreciate this library. It has simplified an absolute ton of workflows for me. I know what it's like to be absolutely slammed at work. Try your best to delegate, maintain balance, and most of all....Keep up the awesome work!

**Comment by ssbarnea** [comment]
That is wonderful library and letting it be affected by bit rot it would be a big loss for python community.

How about moving it under a github organization that can assure its future does not depend on a single person? It could be either one of the existing ones focused on python or a new one. The key here is to find few others that you can trust as not doing anything bad and give them access, so they can help when needed.

That is why none of the libraries I created of maintained with the goal of sharing them are under my personal github account, as I did not want to eventually become the bottleneck.

**Comment by ssbarnea** [comment]
I did not want to imply that pydantic would be into a bad place. I only wanted to do a risk-mitigation measures. Do you have a designated successor configured on https://github.com/settings/admin ? -- that was the kind of issue I wanted to highlight: assuring that everything is set in place in case something bad happens with you, the current pandemy made us more aware of risks.

There is nothing stopping you from having an organization solely for pydantic if you want, they do not cost money.

Regarding use of other organizations, do not see it as "giving away" you project. Some of them were created with the main goal of providing help when needed, not to take away original author control over the project. I am aware of at least three such organizations @sphinx-contrib @pytest-dev and @pycontribs (i bet there are lots more). AFAIK, all of these assure that the author owner keeps his rights, including possibility to transfer it back at any moment. The org admins would step-in to help only when needed, as a fallback. Usually those orgs have an meta repository used for dealing with stuff like this.

There is also the @psf organization, but I am afraid that that one may not suit the project due to its [restricted goal](https://www.python.org/psf/github/) and see 2/4 as not being met for it, likely first of them never will.

BTW, could you please enable discussions option on this repository? It would be great if we could make use of the embedded forum and avoid cluttering the issue tracker with non-issues.

**Comment by samuelcolvin** [comment]
Moved the conversation about hosting/managing pydantic to #2267.
