### ISSUE TITLE
BaseModel init error

### ISSUE THREAD

**Issue by aolefira** [samuelcolvin/pydantic#1916]
# Bug

```
from typing import Union, Optional
from pydantic.main import BaseModel


class A(BaseModel):
    a: Optional[str]


class B(BaseModel):
    b: str


class C(BaseModel):
    c: Union[A, B]


a = A(a='a')
b = B(b='b')

print(C(c=a))
print(C(c=b))
```

Expected output:
```
c=A(a='a')
c=B(b='b')
```

Actual output:
```
c=A(a='a')
c=A(a=None)
```

note: if remove "Optional", pydantic works well

**Comment by PrettyWood** [comment]
Hello @aolefira 
This is a known issue. See #619 and #1423 for more information.
The problem is that it first tries to match with `A` and succeeds as there is no missing value (`a` has a default value `None` and `A` ignores extra parameters by default).
You could fix this by setting in A.Config` `allow_extra = 'forbid'` or by changing the union into `[B, A]`

**Comment by aolefira** [comment]
Thank you! both ways solve my real issue
