### ISSUE TITLE
How can I return different type in dict?

### ISSUE THREAD

**Issue by michaldev** [samuelcolvin/pydantic#1969]
Hi. How can I return different type in dict like in json? (by custom encoder)

I have this model:
```
class MongoBaseModel(BaseModel):
    class Config(BaseConfig):
        json_encoders = {
            ObjectId: lambda oid: str(oid),
            date: lambda d: str(datetime.combine(d, datetime.min.time()).isoformat()),
            datetime: lambda dt: dt.isoformat(),
        }

class UserDB(MongoBaseModel):
    id: Optional[str]
    identifier: str
    sex: SexEnum
    birthday: date
```

I use motor/pymongo, and it required from me dict (not json) format for input data. Date/datetime must be in isoformat, then I should convert my datetime field for it.

When I try with .dict():
`bson.errors.InvalidDocument: cannot encode object: datetime.date(2020, 10, 5), of type: <class 'datetime.date'>`

When I try with .json():
`pymongo.errors.WriteError: Modifiers operate on fields but we found type string instead. For example: {$mod: {<field>: ...}} not {$set: "{"sex": "female", "birthday": "2020-10-05T00:00:00"}"}, full error: {'index': 0, 'code': 9, 'errmsg': 'Modifiers operate on fields but we found type string instead. For example: {$mod: {<field>: ...}} not {$set: "{"sex": "female", "birthday": "2020-10-05T00:00:00"}"}'}`

**Comment by mdavis-xyz** [comment]
Can you provide a full script, including the class definitions and the `.dict()` call that fails?
Something like the second example [here](https://pydantic-docs.helpmanual.io/usage/exporting_models/#custom-json-deserialisation).

I would expect that `.dict()` would not call `json.dumps` at all.
What does the traceback say? Can you paste that in full? (Wrap it in triple backticks so that github formats it nicely.)

**Comment by michaldev** [comment]
```
        await self.db.users.update_one(
            {'identifier': user_identifier},
            {'$set': user.dict(exclude={'id', 'identifier'})}, upsert=True)
```

**Comment by mdavis-xyz** [comment]
What exactly is that snippet? What is `self`? Why doesn't it include the `.dict()` call that you say is causing the failure? What's the full traceback?

Please, help us help you. Please provide a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example). That is, provide an *entire* python script, which I can copy-paste into a file and then run, and I'll then get the exact error you're trying to resolve.

Currently I am not able to run any of your code, because it's not complete. e.g. what is `SexEnum`? If I cannot reproduce your error, I cannot solve it.

**Comment by PrettyWood** [comment]
Please follow the template. We can't help you without more information
