### ISSUE TITLE
Generic Enum attribute fails validations

### ISSUE THREAD

**Issue by choogeboom** [samuelcolvin/pydantic#2063]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7
            pydantic compiled: False
                 install path: /wayfair/home/ch438l/pydantic/pydantic
               python version: 3.6.8 (default, Aug 10 2019, 06:54:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
                     platform: Linux-3.10.0-862.3.2.el7.x86_64-x86_64-with-centos-7.5.1804-Core
     optional deps. installed: ['typing-extensions', 'email-validator', 'devtools']
```

Somewhat hard to explain in words, so check out the following test case

```py
import enum
from typing import Generic, TypeVar

import pydantic.generics


def test_generic_method_return():
    class MyEnumBase(str, enum.Enum):
        pass

    class MyEnum(MyEnumBase):
        a = "a"
        b = "b"
        c = "c"

    E = TypeVar('E', bound=MyEnumBase)

    class InnerClass(GenericModel, Generic[E]):
        my_enum: E

    class OuterModel(GenericModel, Generic[E]):
        my_enum: E

        def create_inner(self) -> InnerClass[E]:
            return InnerClass[E](my_enum=self.my_enum)

    outer = OuterModel[MyEnum](my_enum=MyEnum.a)

    inner = outer.create_inner()
    assert inner.my_enum == MyEnum.a
```

This test fails with the following error message:
```
E           pydantic.error_wrappers.ValidationError: 1 validation error for InnerClass
E           my_enum
E             value is not a valid enumeration member; permitted:  (type=type_error.enum; enum_values=[])
```

This happens because within the `create_inner` method, the type variable has not been replaced with its concrete type, so there's no way for `InnerClass` to know that `E` has been replaced with `MyEnum`. Therefore, it looks at the values of `MyEnumBase` for validation instead.

**Comment by daviskirk** [comment]
I can try and take a look at this if you aren't already since we might face this as well.  I'd like to wait until #1989 is in just to make sure I'm not changing general stuff.

**Comment by choogeboom** [comment]
I haven't had a chance to look at it, so feel free!

**Comment by daviskirk** [comment]
I actually don't think this will work.  Since python has lexical scoping there is no real way to redefine "E" within the scope of the function/method (See https://stackoverflow.com/questions/17862185/how-to-inject-variable-into-scope-with-a-decorator for a discussion on this).  I'm not keen doing any of the stuff they discuss in the thread with the "global scope" as I'm pretty sure that would be completely unmaintainable.

The other possibility would be to store the replaced variables someplace on the class (in `__typevars_map__` for example) and use those in the method... but I would say that is probably also a very special case and also hard to document. 

Currently my intuition is that this should probably not be handled b pydantic since runtime typehints aren't really part of the python language either...
We can of course work around it like this:

```
    class InnerClass(GenericModel, Generic[E]):
        my_enum: E
        def __class_getitem__(cls, params):
            new_cls = super().__class_getitem__(cls, params)
            new_cls.__generic_params__ = params
            return new_cls

        def use_e(self):
            return self.__generic_params__[0]
```

in our own code (or a nicer abstraction if we want). tdyt?

**Comment by samuelcolvin** [comment]
I would agree with @daviskirk that this is beyond pydantic to resolve.
