### ISSUE TITLE
Support for PEP 585 in Python 3.8 and earlier

### ISSUE THREAD

**Issue by layday** [samuelcolvin/pydantic#2112]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

A large number of collection built-ins were made generic in Python 3.9 as part of [PEP 585](https://www.python.org/dev/peps/pep-0585/) and their `typing` module counterparts have been deprecated.  Pydantic supports PEP 585 in 3.9 and above.  Would you consider supporting forward-referenced 3.9-style generics in earlier versions of Python, i.e. when annotations are quoted or with `from __future__ import annotations`?  This might be as simple as creating aliases to `typing` generics in the evaluation context of forward references, overwriting built-ins, in Python 3.8 and below.

**Comment by daviskirk** [comment]
Handling generics and type aliases is already pretty crazy because of the "cutting edge" nature of them being fairly new to python.
Of course I don't know the exact use case and I can imagine that there might be downstream libs that want to support multiple python versions with the same syntax where this might be helpful, but to be completely honest I think it's probably more pain than it's worth to try and backport this feature especially as it the internals of generic aliases will be changing in 3.10 (and 3.11 also).

**Comment by layday** [comment]
That sounds fair enough.  I'll go ahead and close this issue.
