### ISSUE TITLE
Is there a bug here about model field's type.

### ISSUE THREAD

**Issue by x1ah** [samuelcolvin/pydantic#218]
Hi, code like this:

```python
from typing import List
from pydantic import BaseModel


class Foo(BaseModel):
    bar: List[int]

print(Foo.__fields__['bar'].info['type'])
# int
```

shouldn't the type of `bar` be `List[int]` ?

**Comment by samuelcolvin** [comment]
Best to use code formatting in markdown rather than a screenshot so your issue is searchable.

Cause is this:

https://github.com/samuelcolvin/pydantic/blob/8f42e515d536bf9b6d935a2b993d716cdfd13d8b/pydantic/fields.py#L179-L180

this is definitely a problem, particularly for `schema()`:

```py
Foo.schema()
{'type': 'object',
 'title': 'Foo',
 'properties': {'bar': {'type': 'int', 'title': 'Bar', 'required': True}}}
```

as with #213 we need a more sophisticated way to describe types in schema.

**Comment by samuelcolvin** [comment]
Discussion on #213.
