### ISSUE TITLE
Advantages of using pydantic over dataclass?

### ISSUE THREAD

**Issue by Haetsal-Lee** [samuelcolvin/pydantic#2258]
Is the autocomplete key feature of Pydantic? But autocomplete for dataclass is also supported.

I've tried to find the advantages of using the library but failed to find.

**Comment by tutunana** [comment]
> Is the autocomplete key feature of Pydantic? But autocomplete for dataclass is also supported.
> 
> I've tried to find the advantages of using the library but failed to find.

Sorry to provide a link but I think it's sufficient to include all available options you might have: https://stefan.sofa-rockers.org/2020/05/29/attrs-dataclasses-pydantic

**Comment by mvanderlee** [comment]
I looked into Pydantic purely because it's used by FastAPI. But it's a solution looking for a problem IMHO. Marshmallow is much better suited for any needs you may have, and if you want the dataclass syntax, use marshmallow-dataclass.

It does some input validation/deserialization, but does nothing for serialization. It's build in json encoding proved to have severe limitation in my first project.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
