### ISSUE TITLE
Use pydantic to define schema used across services?

### ISSUE THREAD

**Issue by GregDungca** [samuelcolvin/pydantic#2261]
I'm considering using pydantic as the language to define the schema of types shared across services in our team. The schema would be a library that others would import.

I've seen json schema used for this, but pydantic seems like an intriguing choice because we're a Python shop and many developers seem to be happy with pydantic for validation, serialization and de-serialization.

**Is this a suitable use case for pydantic? Any considerations I should make or things to look out for? Thanks in advance.**

My thoughts:
1. Defining types with pydantic comes naturally to my teammates because they're all proficient with Python
2. I like that I can serialize the whole schema as json schema if I need to, but there are some limitations in the features of json schema that pydantic supports, ex. https://github.com/samuelcolvin/pydantic/issues/478
3. pydantic supports the basic schema definition features that I need, ex. inheritance, enums, typing, required fields
4. Alternatively I can define the schema as json schema and then generate the pydantic classes using https://github.com/koxudaxi/datamodel-code-generator/, but [this disclaimer about it being experimental](https://koxudaxi.github.io/datamodel-code-generator/#this-project-is-an-experimental-phase) makes me wary. I've also had users in the past complain about the complexity in the json schema representation if you get carried away with its OOP features
5. It'd be nice to version types, but I might be able to implement that on my own through a suitable naming scheme

**Comment by daviskirk** [comment]
If you are a python shop I'd think https://github.com/koxudaxi/datamodel-code-generator/ might make things overly complex and harder to make "nice" since you also loose a few other more advanced pydantic features.
The other way around is probably easier, and I've used pydantic models as a base to produce jsonschema that is then used by non-python projects (that way around the code seems to be very stable, and as far as I know fastapi uses exactly this method as well to generate parts of it's openapi schemas).  
There's also https://github.com/phillipdupuis/pydantic-to-typescript in cases you want to use pydantic models in typescript code (but for any of those you'd have to make sure all of this is automated and checked well in CI, and of course the community around those tools are smaller than "base" pydantic).

**Comment by koxudaxi** [comment]
@daviskirk 
I agree.

@GregDungca
I'm the author of `datamodel-code-generator`
> Alternatively I can define the schema as json schema and then generate the pydantic classes using https://github.com/koxudaxi/datamodel-code-generator/, but this disclaimer about it being experimental makes me wary. 

I may change the generated model or interface future version.
because I want to improve the features and interface.

However, The code-generator is downloaded by a lot of users ([18k downloaded per month](https://pepy.tech/project/datamodel-code-generator)).
I keep the generated model and interface as possible as in the same major version.
If you use it in your production project then you should pin a version.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).

**Comment by GregDungca** [comment]
@daviskirk and @koxudaxi. Thanks for the replies. 

We went ahead with implementing a system that allows users to define schemas in library that uses Pydantic with a CI job that dumps the schemas into jsonschema. Services have the option of using the schema via the library or by retrieving the jsonschema (the latter leverages `datamodel-code-generator`). We'll see how well this system serves our use cases. Thanks again!
