### ISSUE TITLE
Unpickleable models

### ISSUE THREAD

**Issue by sbv-csis** [samuelcolvin/pydantic#2342]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question
I'm having problems with unpickleable models. Here's a very simple example:

```py
from pydantic import BaseModel, stricturl
import pickle

class M(BaseModel):
    url: stricturl(tld_required=True)

pickle.dumps(M(url='https://google.com'))
``` 
which leads to
``` 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class '__main__.UrlValue'>: attribute lookup UrlValue on __main__ failed

Can't pickle <class '__main__.UrlValue'>: attribute lookup UrlValue on __main__ failed
``` 

I'm not sure how to best get this to be pickleable

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: <--redacted-->/lib/python3.9/site-packages/pydantic
               python version: 3.9.1 (default, Jan 11 2021, 09:52:32)  [GCC 9.3.0]
                     platform: Linux-5.4.0-65-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by davidhyman** [comment]
Dynamic types don't play well with pickle.

This is, I think, specifically due to the `stricturl` implementation only - it dynamically generates the `UrlValue` type, and pickle doesn't like things it can't reference in the module (how would it unpack it? how could it be sure it was always the same class returned?). Much like lambdas. I've no idea what the provenance of `stricturl` is; presumable it's handy for dynamic class generation with all the possible combinatorics of validation configuration that it exposes.

Seems the only difference with `AnyUrl` is that `tld_required=True`; so a fix, either in your code or as a contribution to `networks.py`, would be something like:

```
class StrictUrl(AnyUrl):
    tld_required: bool = True
```
and your demo code would become:
```
class M(BaseModel):
    url: StrictUrl
```
which works for me (gives `b'\x80\x04\x95\x16\x01 ... `)

Of course the downside is that maybe there are too many use cases and differences as to what one would consider 'strict' for there to be only one StrictUrl defined in pydantic, so perhaps best left to the downstream project.

references:
https://github.com/samuelcolvin/pydantic/blob/a1ac464371bb9ac642f6e9b531cb787e2a8142c6/pydantic/networks.py#L105

https://pydantic-docs.helpmanual.io/usage/exporting_models/#pickledumpsmodel

https://pydantic-docs.helpmanual.io/usage/types/#urls
