### ISSUE TITLE
Hypothesis ignores regex in constr

### ISSUE THREAD

**Issue by bofm** [samuelcolvin/pydantic#2435]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8
            pydantic compiled: True
                 install path: /Users/x/.virtualenvs/x-QcOdTB3U/lib/python3.8/site-packages/pydantic
               python version: 3.8.1 (default, Feb 11 2020, 15:55:53)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

```py
from hypothesis import strategies as st
from pydantic import BaseModel, constr


class X(BaseModel):
    a: constr(regex='a')

st.builds(X).example()
# pydantic.error_wrappers.ValidationError: 1 validation error for X
# a
#   string does not match regex "a" (type=value_error.str.regex; pattern=a)

st.from_type(X).example()
# pydantic.error_wrappers.ValidationError: 1 validation error for X
# a
#   string does not match regex "a" (type=value_error.str.regex; pattern=a)
```

It is expected that hypothesis would generate strings that match the regex.

**Comment by PrettyWood** [comment]
Hi @bofm 
_pydantic_ uses [`re.match()`](https://docs.python.org/3/library/re.html#re.match) to validate a string, which needs the pattern to be at the beginning of the string.
I think the best is to actually use `^a` instead of `a` to ask Hypothesis to generate valid strings.
The good news is that is will be changed in https://github.com/samuelcolvin/pydantic/issues/1631. So Hypothesis plugin is already working as expected

**Comment by bofm** [comment]
Hi @PrettyWood 

Ah, I see. Without `^` Hypothesis seems to not be able to generate a properly matching string. Thank you.
