### ISSUE TITLE
Different flavors of dataclass

### ISSUE THREAD

**Issue by pauleveritt** [samuelcolvin/pydantic#244]
I've been watching #231 with great interest. I suspect I'm on the edge of the 20th rewrite of my (unreleased, pydantic-based) CMS project for Sphinx.

Based on an example in that PR's tests, let's say I have:

```python
@pydantic.dataclasses.dataclass
 class Article(BaseResource):
     title: str
```

Let's say, though, that Article is a kind of Resource. I might have other Resources: Author, Topic, etc.

Let's then say there are other kinds of kinds of things. Not just Resource...View, Reference, etc. I could do this:

```python
@mything.resource
@pydantic.dataclasses.dataclass
 class Article(BaseResource):
     title: str
```

...and put my extra registration stuff in ``mything.resource``. But could I subclass ``pydantic.dataclasses.dataclass`` and do:

```python
@mything.resource
 class Article(BaseResource):
     title: str
```

I know there's tons of meta stuff going on. I suspect that wouldn't fly.

**Comment by samuelcolvin** [comment]
One of the problems with the decorator approach is that it makes inheriting and modifying the decorator almost impossible.

Much better to put your extra logic in `BaseResource`.

But then:
* why not use standard `BaseModel` from pydantic where inheritance and modification is relatively? It's also fewer lines of code and arguably cleaner and more readable.
* (none of my business, but) in my experience putting to much logic in classes like this can lead to confusion. I made the mistake of putting masses of logic in django `Model` classes years ago and we're still dealing with the results. As projects grow it's often easiest to just have a simpel dumb method that does something that you can call and unit test and otherwise ignore.

Closing this as it's not really an issue with pydantic, but feel free to ask any follow up questions here.
