### ISSUE TITLE
No PEP 604 support (e.g. str | None instead of Optional[str])

### ISSUE THREAD

**Issue by gjcarneiro** [samuelcolvin/pydantic#2453]
Hi, I installed mypy 0.800, and it supports PEP 604, which should allow types like "str | None", instead of Optional[str].  Pydantic doesn't seem to like it.

https://mypy-lang.blogspot.com/2021/01/mypy-0800-released.html

### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8
            pydantic compiled: True
                 install path: /app/env/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
                     platform: Linux-5.8.0-44-generic-x86_64-with-glibc2.29
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
from __future__ import annotations

from decimal import Decimal
import pydantic

class FinanceOverviewCell(pydantic.BaseModel):
    # pl_gbp: Optional[Decimal]
    pl_gbp: Decimal | None
```

The result is:
```
Traceback (most recent call last):
  File "foo.py", line 6, in <module>
    class FinanceOverviewCell(pydantic.BaseModel):
  File "pydantic/main.py", line 270, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 282, in pydantic.typing.resolve_annotations
    """Mixin to prohibit subclassing"""
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by PrettyWood** [comment]
Hi @gjcarneiro 
It won't be directly possible because the `future` implementation is just for annotation but can't be used at runtime !
So it's useful for `mypy` but can not be leveraged for runtime inspection.
Only with python 3.10 can _pydantic_ leverage this and support the new `types.Union` (and not `typing.Union`)
A solution would be to rewrite at interpretation time `|` into `Union` for python version prior to 3.10 (I actually did a quick implementation of it https://github.com/PrettyWood/future-typing but it still requires some work) and it _could_ maybe be used some day but definitely not now!

**Comment by PrettyWood** [comment]
@gjcarneiro FYI https://github.com/samuelcolvin/pydantic/pull/2609 :)
