### ISSUE TITLE
BaseSettings alias config not working

### ISSUE THREAD

**Issue by jasonkuhrt** [samuelcolvin/pydantic#275]
pydantic version `0.14`

```
❯ export test=foobar; pipenv run python
Python 3.6.1 (default, Aug  1 2018, 10:30:03)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import pydantic
>>> class S(pydantic.BaseSettings):
...   test:str
...   class Config:
...     fields = dict(test=dict(alias="test"))
...
>>> S()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jasonkuhrt/.local/share/virtualenvs/waldo-QOik3jd4/lib/python3.6/site-packages/pydantic/env_settings.py", line 35, in __init__
    super().__init__(**values)
  File "/Users/jasonkuhrt/.local/share/virtualenvs/waldo-QOik3jd4/lib/python3.6/site-packages/pydantic/main.py", line 166, in __init__
    self.__setstate__(self._process_values(data))
  File "/Users/jasonkuhrt/.local/share/virtualenvs/waldo-QOik3jd4/lib/python3.6/site-packages/pydantic/main.py", line 331, in _process_values
    return validate_model(self, input_data)
  File "/Users/jasonkuhrt/.local/share/virtualenvs/waldo-QOik3jd4/lib/python3.6/site-packages/pydantic/main.py", line 507, in validate_model
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 1 validation error
test
  none is not an allow value (type=type_error.none.not_allowed)
>>> os.getenv('test')
'foobar'
```

Expected that `test` would be parsed as str of `foobar`.

**Comment by samuelcolvin** [comment]
This is a bug.

Because the alias `test` matches the name of the field, `field.alt_alias` 

https://github.com/samuelcolvin/pydantic/blob/cd50601172462b49cdf09e4d988906ba8f14af87/pydantic/env_settings.py#L43

Is `False`.

Shouldn't be too hard to fix. PR welcome, otherwise I'll fix when I get a chance.

**Comment by jasonkuhrt** [comment]
Relatedly...

What drove the code sample above was a desire to change case semantics. Maybe there could be two options in config:

1. lower_case
2. upper_case (default)
3. case_insensitive

**Comment by samuelcolvin** [comment]
I'm very keen. I spend a lot of my time rewriting env variables to upper case.

The only slight problem I can see is that it's not entirely trivial to do the `case_insensitive` case, since env is case sensitive.

I guess the code could just do

```py
env2 = {k.lower(): v for k, v in os.environ.items()}
```
Then work with `env2`, but is there ever a chance that `os.environ` could be big enough to cause memory problems? I have no idea.
