### ISSUE TITLE
1.9.0a1  breaks workaround for `field_type_schema` and nullable

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#3546]
release 1.9.0a1  breaks this work around completely:

```python
.../inmanta/data/model.py", line 34, in <module>
    old_field_type_schema = pydantic.schema.field_type_schema
AttributeError: 'cython_function_or_method' object has no attribute 'field_type_schema'
```

_Originally posted by @wouterdb in https://github.com/samuelcolvin/pydantic/issues/1270#issuecomment-997700804_

**Comment by arnaudsjs** [comment]
I think this issue has the following root cause:

* The `pydantic/main.py` file defines a function called `schema`
* The `pydantic/__init__.py` file does the import `from .main import *`

As such the following import `from pydantic import schema` imports the function `schema` and not the package `schema` which also exists in the `pydantic` package.

Illustration:
```
(env) [arnaud@laptop]/tmp% pip install pydantic==1.8.2  
...
Successfully installed pydantic-1.8.2
(env) [arnaud@laptop]/tmp% python
>>> from pydantic import schema
>>> print(schema)
<module 'pydantic.schema' from '/tmp/env/lib64/python3.6/site-packages/pydantic/schema.cpython-36m-x86_64-linux-gnu.so'>

(env) [arnaud@laptop]/tmp% pip install -U --pre pydantic
...
Successfully installed pydantic-1.9.0a1
(env) [arnaud@arnaud]/tmp% python
>>> from pydantic import schema
>>> print(schema)
<cyfunction schema at 0x7fec8df76d50>
```
