### ISSUE TITLE
BaseSettings - pylance complains for not setting default values to fields

### ISSUE THREAD

**Issue by calvo-jp** [samuelcolvin/pydantic#3753]
Hi! I am a huge fan. I am just encountering an error at the moment. The code below used to have no issue with `pylance` using previous `pydantic` version. But, right now I can no longer create an instance without having to pass values to fields that are supposed to be set only in `.env` or loaded from environment. It is really nice that it now offers autocomplete (same goes to `BaseModel`) and it actually still works. It's just that I really do not like the view of squiggly lines :smile: Would there be a quick fix for this?

![Screenshot from 2022-01-30 10-12-43](https://user-images.githubusercontent.com/86353187/151684408-8c87b74e-cd20-45d9-9679-1642293cac9c.png)

These are my `vscode` settings, btw.

```json
"python.analysis.typeCheckingMode": "basic",
"python.languageServer": "Pylance",
```

Thank you in advance for your response.

**Comment by marianhlavac** [comment]
Duplicate of #3617 – it's related to the use of `Field()`

**Comment by calvo-jp** [comment]
I see. I never had problems with `Field` and `BaseModel`, tho. I always do it like so

```python
class Model(BaseModel):
    optional_field1: Optional[int] = None
    optional_field2: Optional[str] = ""
    optional_field3: Optional[str] = Field(default="") # using positional arg for default here does not work
```

**Comment by marianhlavac** [comment]
Well, apparently not just using Field, as mentioned in #3767

**Comment by squaresmile** [comment]
A workaround for this is to use `= Field(default=...)` for required parameter and `= "literal value"` or `= Field(default="default")` for optional parameter. 
- The required case will trick pyright into thinking the field is optional. 
- For the optional case, it's necessary to use the keyword argument `default` if the function `Field` is used because of how [`dataclass_transform` was implemented](https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md#field-descriptors).

**Comment by samuelcolvin** [comment]
I've emailed Eric Traut, the developer of pyright to ask about this. Hopefully he provides some way to disable dataclass transforms on subclasses of `BaseSettings`.

**Comment by samuelcolvin** [comment]
Here's the response from @erictraut about this, here's our conversation:

me:

> ...
> 
> I wonder if it's possible to disable dataclass transforms (or at least pyright recognising them) on some subclasses of a class which is decorated with `@__dataclass_transform__`?
> 
> The issue is described in #3753 - basically pydantic's `BaseSettings` class can be initialised from environment variables and hence "required" fields do not need to be provided when initialising the class. However since `BaseSettings` inherits from `BaseModel`, pyright and pylance are complaining that fields are missing.
> 
> Is there any way of deactivating dataclass transforms on subclasses of `BaseSettings`?
> 
> ...

Here's Eric's response:

> No, `dataclass_transform` doesn’t provide any such facility. That would deviate significantly from the behavior of stdlib dataclass, so I don’t think there would be much appetite for supporting it.
> 
> I would recommend to pydantic users that they don’t make use of dynamic behaviors like initialization from .env variables if they want to use pydantic with static type checking. Alternatively, they (or you) could use a static conditional (e.g. `if TYPE_CHECKING`) to define BaseSettings in a way that it doesn’t derive from BaseModel.
> 
> I’ve include Erik de Bonte on the thread. He’s the primary author of PEP 681, and I want to make sure he’s aware of the issue you’re raising.
> 
> We’re running a bit short on time to get PEP 681 accepted prior to the deadline for Python 3.11, but the good news is that Erik submitted the PEP to the Python steering council (SC) last Friday. We’re hoping to receive word within the next couple of weeks that it has been accepted. It’s probably too late to amend it at this time unless we identify a problem that is so big that we would be willing to risk slipping beyond 3.11.

**In Summary**: There's no way to disable the dataclass transform logic on classes which inherit from `BaseSettings`.

There are therefore two work around:

```py
settings = Settings.parse_obj({})
# or
settings = Settings()  # pyright: ignore
```
I don't this is is too bad - because of pydantic's lax/coercion approach to data validation, you'll already need to do a fair bit of ignoring pyright, this is no exception.

I've created a PR #3972 to test pyright against pydantic code in CI so we can make sure the behaviour doesn't change (or at least is formalised)

**Comment by samuelcolvin** [comment]
feedback welcome on #3972

**Comment by florian-sattler** [comment]
I think the PR is good so far, however I don't think the proposed solution
```python
settings = Settings.parse_obj({})
```
makes it very obvious what is happening. Perhaps adding a dedicated method like one of the following would be handy.

Idea 1:
```python
    @classmethod
    def from_env(cls):
        return cls.parse_obj({})
```

Idea 2:
```python
    @classmethod
    def parse_env(cls):
        return cls.parse_obj({})
```

Idea 3:
```python
    @classmethod
    def parse_env(cls, defaults=None):
        obj = {} if defaults is None else defaults
        return cls.parse_obj(obj)
```

I know adding this might be a stretch and might also introduce some issues later down the line, when the underlying get resolved in the future.

**Comment by samuelcolvin** [comment]
humm, this was my initial idea, however:
1. I'm not keen to add another method just to work around an issue in a type checker - not even the most popular python type checker
2. I think it could be even more confusing for those new to pydantic than the current behaviour "what's so special about `parse_env()`?"
3. Adding new public methods to `BaseModel` and `BaseSettings` is somewhat dangerous, see [this dicussion](https://discuss.python.org/t/better-fields-access-and-allowing-a-new-character-at-the-start-of-identifiers/14529)

I'd be happy to remove the `settings = Settings.parse_obj({})` hack from the docs - can you comment on the PR, rather than here so I remember to change it.

**Comment by marianhlavac** [comment]
> I'm not keen to add another method just to work around an issue in a type checker

Not only this has the chance to resolve the type checking issue, but some users might prefer this, as this will explicitly note that the settings object is constructed from environment variables (which might not be immediately obvious for users new to Pydantic, typing `settings = Settings()` might leave them thinking it will make an empty model).

> Adding new public methods to BaseModel and BaseSettings is somewhat dangerous

How terrible idea it would be to keep the "from_env" method separate from the class, receiving BaseSettings instance just as an argument?

```python
from pydantic.env_settings import build_from_env

settings = build_from_env(Settings)  # returns Settings
# or
settings = Settings()
```

It's not as elegant as `Settings.from_env()`, but also it wouldn't be the primary way to build the settings objects, the `settings = Settings()` would be still the recommended way to go. But of course this might confuse some users, as they might ask "should I use Settings() of build_from_env(Settings)?"

**Comment by hoetmaaiers** [comment]
No working solution is typed out, so I give it a try. The type checker workaround solution would be: 

```python
class Settings(BaseSettings):
    title: str
    ...

    model_config = SettingsConfigDict(env_file_encoding="utf-8", env_file=".env")

settings = Settings.model_validate({})
```

I read about `parse_obj(())` but this is deprecated by `model_validate()`. It remains a workaround though... 

Maybe @samuelcolvin can provide an even better _satisfy the type checker solution_?

**Comment by zobweyt** [comment]
To work around this error, you can use `Field(init=False)` if you don't need to manually pass settings elsewhere (it works similar to [`dataclasses.Field(init=False)`](https://docs.python.org/3/library/dataclasses.html#dataclasses.field)).

```python
from pydantic import Field
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    title: str = Field(init=False)


settings = Settings()
```

The error disappears as it removes `title` from the constructor.

**Comment by Piotrulaa** [comment]
I think this is a pretty elegant solution to this problem:

```python
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    setting: str


def get_settings(**kwargs) -> Settings:
    return Settings(**kwargs)


settings = get_settings()
```
