### ISSUE TITLE
Documentation for "Postponed Annotations" is slightly confusing

### ISSUE THREAD

**Issue by theenglishway** [samuelcolvin/pydantic#486]
Pydantic version : 0.23

I find [this paragraph regarding postponed annotations](https://pydantic-docs.helpmanual.io/#postponed-annotations) a bit confusing.

1. The first example works even without the import, and does not even demonstrate the feature IMO ?!

```
from __future__ import annotations # Useless !
from typing import List
from pydantic import BaseModel

class Model(BaseModel):
    a: List[int] # Where's the forward reference ?

print(Model(a=('1', 2, 3)))
#> Model a=[1, 2, 3]
```

2. It wasn't immediately clear to me that the two suggested solutions (with annotations and ForwardRef) were completely independent indeed (I ended up on #234 after googling "python typing ForwardRef") 

3. I use Python 3.7.3 and yet have no such thing as ForwardRef in the typing module ? I'm completely unaware of type annotation's internals, but is that solution still relevant ? 

Since the first solution works like a charm, I'll be suggesting a PR which emphasizes on it and updates the example

**Comment by samuelcolvin** [comment]
You've slightly missed the point in `from __future__ import annotations` I think.

Maybe we could make that clear clearer.

if you have

```py
class Foo:
    a: int
```

The annotation on `Foo.a` is `int`, eg. the base type, the one that does tricks like `int('1')` and `isinstance(x, int)`.

If instead you have,
```py
from __future__ import annotations

class Foo:
    a: int
```

Then the annotation to `Foo.a` is literally the string `'int'` eg. a string with three characters `i`, `n` and `t`. 

This is supposed to reduce the memory footprint very slightly (although personally I would say if you're that close to a memory limit it's time to rewrite your application in another language or go out and buy some more ram).

The point is that in the past pydantic burst into tears when you used `from __future__ import annotations` because it was expecting types for annotations and got strings. #348 fixed that by evaluating to get those strings to convert them to types.

`update_forward_refs()` just deal with the case where the evaluation of strings to types doesn't work because you haven't yet defined the type you want to evaluate.

Does that make sense?

**Comment by theenglishway** [comment]
Damn you're fast !

As I said I'm completely unaware of the internals but your explication couldn't be any clearer, I think I now understand what that paragraph is all about :+1: 

As a I-just-wanna-use-that-great-library-and-not-know-the-internals user, my main reason for reading this part of the documentation was that I fell into the "self-referencing" annotation case which is solved by `update_forward_refs` and had the intuition that it was somehow relevant 

And in that regard I would say that the documentation has room for improvements, maybe by : 

1. making it clearer that the example with `from __future__ import annotations` is just there to show that it used not to work but works great now (and I would even say that as a user I almost don't need to know it since it " just works" as expected :) )
2. rewriting the paragraph regarding `ForwardRef` which ... doesn't seem relevant any more ? 

Regarding point 2., and unless I've missed something (again !), the example in the documentation : 

```
from typing import ForwardRef
from pydantic import BaseModel

Foo = ForwardRef('Foo')

class Foo(BaseModel):
    a: int = 123
    b: Foo = None

Foo.update_forward_refs()
```
... can be rewritten as : 
```
from pydantic import BaseModel

class Foo(BaseModel):
    a: int = 123
    b: 'Foo' = None

Foo.update_forward_refs()
```
or as :
```
from __future__ import annotations
from pydantic import BaseModel

class Foo(BaseModel):
    a: int = 123
    b: Foo = None

Foo.update_forward_refs()
```
... which both work perfectly (with Python 3.7.3 at least) and are more concise 

What do you think ? 
(and is there a case where using `ForwardRef` is mandatory ?)

**Comment by samuelcolvin** [comment]
> and is there a case where using ForwardRef is mandatory

Not that I know of.

That looks good to me, PR welcome. You might want to update your fork since I've just released v0.24.

**Comment by theenglishway** [comment]
Another idea could be a separate paragraph on self-referencing models, maybe ?

And yup, I'll update my PR using that new knowledge !

**Comment by samuelcolvin** [comment]
yup, makes sense.
