### ISSUE TITLE
Separate input/output aliases

### ISSUE THREAD

**Issue by Midnighter** [samuelcolvin/pydantic#492]
# Feature Request

Coming from marshmallow there are a number of questions/feature ideas so I hope this is not too spammy. Currently, pydantic allows (de-)serializing using attribute aliases which means that if I want to deserialize from one alias and serialize to another one, I need two models:

```
objA[JSON] -> InModel[BaseModel] -> OutModel[BaseModel] -> objB[JSON]
```

in marshmallow instead I can specify separate aliases such that above manipulations become:

```
objA[JSON] -> Model[BaseModel] -> objB[JSON]
```

I completely understand if this is low priority right now but do you think this is desirable at all?

**Comment by samuelcolvin** [comment]
it wouldn't be hard to do either using `Config.fields` or `Schema`.

Let's see if other people what this...

**Comment by Charlie-iProov** [comment]
Im wondering if this covers something similar to what im experiencing - fields in an object contain hyphens which are not python compatible when defining variables in my model.  I therefore have been using the config field to reformat the hyphens to underscores. However, this means I have to do some manipulation when inserting my object into a DB as now the output of my object contains underscores due to the models config. Therefore i must reformat the underscores back to their respective hyphens. Is there a way of setting an alias for a model so that objectA(hyphenated) > Model (underscored) > ObjectB(aliased & hyphenated again)?

**Comment by samuelcolvin** [comment]
can't you just use `dict(by_alias=True)`?

**Comment by Charlie-iProov** [comment]
It would appear that this is likely user error on my part although having used `dict(by_alias=True)` i dont seem to be able to invoke the change to utilise the alias. I'll dig into your docs more tomorrow to see if I can fix. thanks for the quick reply
