### ISSUE TITLE
HtmlColor validator

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#504]
Eg. [named colours](https://www.w3schools.com/colors/colors_names.asp)

or hex, or rgb, or rgba.

I guess we have to use the american spelling for colour. :disappointed:

**Comment by pilosus** [comment]
I would suggest using [CSS3 spec](https://www.w3.org/TR/css-color-3/#svg-color) colour names. They are also defined in [SVG spec](https://www.w3.org/TR/SVG11/types.html#ColorKeywords).

I also have got a couple of questions regarding this issue:
1. Should the validator *only validate* that a colour given is among the set of the named colours?
2. What formats exactly we should support?

This is what I've come up with:

```
from pydantic import BaseModel, HtmlColor

class Model(BaseModel):
    color: HtmlColor = None


# all these are valid colours, actually variant represent 'antiquewhite'
name_color = Model(color='antiquewhite')
name_color2 = Model(color='AntiqueWhite')  # case ignored
hex_color = Model(color='0xfaebd7')
hex_color2 = Model(color='#faebd7') # also hex
hex_color3 = Model(color='#FAEBD7') # letter's case ignored
rgb_color = Model(color=(250, 235, 215))
# we just ignore alpha-channel if first 3 ints match
rgba_color = Model(color=(250, 235, 215, 10))  
```

Should we support RGB/RGBA as stings? Something else I'm missing?

**Comment by samuelcolvin** [comment]
all those cases look good a few more we should probably accept:
* `fff` eg. three letter html colours
* `rgb(1,1,1)` and `rgba(1,1,1,0)` should also work, shouldn't be too hard with a regex

It looks like you can also definite colours using `hsl(...)` and `cmyk(...)` but I really think that's too niche for now.

The other case is how does the parsed value `m.color` behave, eg. is it just a string or an rgb tuple?

I think best that we return an instance of `HtmlColor` which doesn't inherit from string, but where the `__str__` method returns a valid html string.

Another question: should we always validate to the same thing or leave the output format as it came in? Eg. if someone enters `rgb(0, 0, 0)` should we return:
* `rgb(0, 0, 0)`
* `#000` or `#000000`
* or `black`
?

Genuinely not sure what's best here. I think we have to have:
* `original()` which returns the original value passed to the model
* `as_hex()`
* `as_rgba()`
* `as_tuple()` - should this be 3 or 4 values or always 4?
* `as_named_color()`
* and perhaps `best()` (better name needed) which tries named colour but falls back to hex if no name or rgba if there's an alpha channel
* should `__str__` be an alias of `original()` or `best()`?

Turns out this is much more complicated than I thought, but quite fun :-)

**Comment by pilosus** [comment]
@samuelcolvin ``hsl(...)`` is easy to implement using [colorsys](https://docs.python.org/3/library/colorsys.html) from the standard library, though some conversion will be needed as ``colorsys`` gets ``rgb`` as all floats of range ``0.0..1.0``. ``colorsys`` also lacks  ``cmyk(..)``.

By the way, it seems that defining ``rgb/rgba`` as a tuple of all floats is quite common. So this probably should be supported too, e.g. ``rgb(0.1, 0.3, 0.2)`` and ``rgba(0.1, 0.3, 0.2, 0.1)``

Another thing that I've just realised is that if we do all these fancy conversions, we have to take care of [alpha composition](https://en.wikipedia.org/wiki/Alpha_compositing). We cannot just drop alpha from ``rgba`` and match ``rgb`` against a set of allowed colours (except for the case where alpha = 1.0). There should be a conversion rgba->rgba done first (see [this post](https://stackoverflow.com/questions/2049230/convert-rgba-color-to-rgb) for more details).

> Another question: should we always validate to the same thing or leave the output format as it came in? 

I would certainly expect the output format match the input's one. I think a user can add conversion to the needed format at a post validation step.

> as_rgba()
What if ``as_rgba()`` always returns ``rgba`` (with alpha = 1.0 in ``rgb`` case). Then we also add ``as_rgb()`` method to only return ``rgb`` (there will be a conversion for ``rgba`` case here).

> as_tuple()
May be also splitted as ``as_rgb_tuple()`` and ``as_rgba_tuple()``?

> as_named_color()
Return a lower cased name of the colour passed

> best() [...]  tries named colour but falls back to hex if no name or rgba if there's an alpha channel
This brings us to the first question I've asked: if we only validate that a colour passed is in the set of predefined colours defined in CSS3/SVG specification? Or we just try to validate a colour returning it's predifined name if we can find it, otherwise we fall back to ``hex`` or ``rgba``?

> should __str__ be an alias of original() or best()?
I woud go for an alias of ``original()``

I think it's also worth taking a look at the [webcolors](https://pypi.org/project/webcolors/) package as well as [maplotlib.color API](https://matplotlib.org/2.0.2/api/colors_api.html)

**Comment by samuelcolvin** [comment]
> This brings us to the first question I've asked: if we only validate that a colour passed is in the set of predefined colours defined in CSS3/SVG specification?

Yes, we're checking it's in the list of predefined colours from css3.

We don't want to do any clever stuff with the alpha channel, if it's there (and not 1.0/255) the colour has to be defined as `rgba(...)`, no hex, no names.

We can happily ignore `cmyk`, look at how github interprets hex, rgb, rgba and hsl but not cmyk.

`as_rgb` and `as_hex` should fail if there's an alpha channel, same as `as_named_color` should fail if there's no such named colour.

> May be also splitted as as_rgb_tuple() and as_rgba_tuple()?

Let's just call it `as_tuple` and add a keyword argument `alpha` which can be `include`, `exclude` or `auto`, default to `auto`.

**Comment by samuelcolvin** [comment]
maybe we should call the field `Color` since it's not just html, but also css, svg and many other related technologies.

**Comment by pilosus** [comment]
@samuelcolvin ok, now it's clear. Also agree with ``Color``!

I would work on this issue if you don't mind

**Comment by samuelcolvin** [comment]
yes please.

For clarity I think `Color` should only need three slots:

```py
class Color:
    __slots__ = '_rgba', '_original', '_color_match'

    def __init__(...):
        self._rgba: Tuple[int, int, int, Optional[int]] = ...
        self._original: str = ...
        self._color_match: Union[str, None, bool] = None # used to cache the named color or that there is none
```

Obviously do it how you think best, but I think the above makes sense as a starting point.
