### ISSUE TITLE
Field representation does not show generic types.

### ISSUE THREAD

**Issue by proofit404** [samuelcolvin/pydantic#505]
I tried to run this code on https://github.com/samuelcolvin/pydantic/commit/bff8a1789dfde2c38928cced6640887b53615aa3

![Untitled](https://user-images.githubusercontent.com/1862725/57166070-a728c380-6e01-11e9-9544-a57a4799a2b8.png)

As you can see field representation does not say `List[int]`

Thanks for an awesome package.

**Comment by samuelcolvin** [comment]
The problem here is that `field.type_` holds information and about the items in that field (eg. `int` here) and `field.shape` holds information about the "shape" of the data, eg. list, dict, set etc.

Basically `field.__str__` could use some work.

https://github.com/samuelcolvin/pydantic/blob/bff8a1789dfde2c38928cced6640887b53615aa3/pydantic/fields.py#L449-L459

But I don't think this is a big urgent problem.
