### ISSUE TITLE
Type erasure in parametrized sequences like List[Union[T, T1,…]]

### ISSUE THREAD

**Issue by Orhideous** [samuelcolvin/pydantic#54]
Version: pydantic 0.3
```python
from typing import Union, List
from pydantic import BaseModel


class First(BaseModel):
    a: int = 1


class Second(First):
    b: str = 2


class Container(BaseModel):
    c: List[Union[First, Second]] = []


first = First()
second = Second()

container = Container(c=[first, second])

assert type(container.c[0]) == First
assert type(container.c[1]) == Second, "Type erasure!"
```

**Comment by samuelcolvin** [comment]
Thanks for reporting the issue.

There are actually two problems here, one completely unrelated to pydantic, one related to the way you're using it.

## 1

First, `Union[First, Second] == First` this is not related pydantic but just part of how the standard libraries typing works, because `Second` inherits form `First` typing simplifies the statement to just be the "top" type:

```python
from typing import Union

class Foo:
    pass

class Bar(Foo):
    pass

print(Union[Foo, Bar])
# > <class '__main__.Foo'>
print(Union[Foo, Bar] == Foo)
# > True
```

So the code above is really just

```python
class Container(BaseModel):
    c: List[First] = []
```

Which explains the result you're getting.

## 2

Consider a slightly different case which you might expect to work

```pydantic
from typing import Union, List
from pydantic import BaseModel

class First(BaseModel):
    a: int = 1

class Second(BaseModel):
    b: str = 'x'

class Container(BaseModel):
    c: List[Union[First, Second]] = []

container = Container(c=[First(), Second()])
print(container)

assert type(container.c[0]) == First
assert type(container.c[1]) == Second, "Type erasure!"
```

Here the Union is real, eg. it initialises to a union not just a simple type so you might expect `container.c[1]` to be an instance of `Second`. However it's still not.

Pydantic is designed to validate external data, generally json/xml/mspack etc. eg. recursive structures of dicts, lists and simple types. More complex objects can be processed but generally only if they duck type to a list/dict/string/int etc. or if you implement custom validators.

In this case the expected type for a sub-model is a dict, you can see this by printing information about the fields:

```python
class First(BaseModel):
    a: int = 1

class Container(BaseModel):
    c: First

print(Container.__fields__)
# > OrderedDict([('c', <Field c: type='First', required=True, validators=['dict_validator', 'BaseModel.validate']>)])
```
Note `validators=['dict_validator', 'BaseModel.validate']`.

In other words pydantic will first try to cast the object to a dict (see [here](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/validators.py#L74), then check if it is a valid `First`.

In your case both models `First` and `Second` have no required fields and ignore extra fields so the two dicts returned `dict(First()) > {'a': 1}` and `dict(Second()) > {'b': 'x'}` are both valid as inputs to both `First` and `Second`. Pydantic returns the value given by the first successful track which is `First`.

Either add `ignore_extra = False` or make the only field in each model required and it works fine:

```python
from typing import Union, List
from pydantic import BaseModel

class First(BaseModel):
    a: int = 1

    class Config:
        ignore_extra = False

class Second(BaseModel):
    b: str = 'x'

    class Config:
        ignore_extra = False

class Container(BaseModel):
    c: List[Union[First, Second]] = []

container = Container(c=[First(), Second()])
print(container)

assert type(container.c[0]) == First
assert type(container.c[1]) == Second, "Type erasure!"
```

I'm going to close this as I don't think there's anything to change in pydantic, but if you have any more questions (with some more context on what you're trying to do), feel free to reply and I'll try to help.
