### ISSUE TITLE
MacOS and windows pre-compiles binaries

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#555]
pydantic will soon be compiled with cython, however pre-compiled binaries are only available on linux at the moment.

It should be possible for macos on travis and windows on azure pipeline.

However since I only use linux, it's not my primary concern.

I'd be happy to accept a PR if someone is prepared to implement one or both.

**Comment by anentropic** [comment]
Just a note, the current "cythonize" step which happens in setup.py gave me the cythonized version of pydantic by default, via wheel, when I `pip install pydantic` on macos.

This is all great, but I noticed because I was trying to debug something and the cythonized code does not play well with ipdb - you get a stack trace ok but any values you try to inspect give `NameError`.

To get a plain python version of pydantic I could do this:
```
pip uninstall pydantic
export SKIP_CYTHON=1
pip install --no-cache-dir --no-binary :all: pydantic
```

If things change in future it'd be nice to still have a way to install non-cythonized pydantic if necessary.

To be clear, I'm quite happy getting the cythonized version by default though.

**Comment by samuelcolvin** [comment]
thanks for pointing out this should have already been closed.

You can install non compiled pydantic with

```shell
pip install --no-binary pydantic pydantic
```
I think you'll also need to either not have cython installed or use `SKIP_CYTHON=1`.

**Comment by samuelcolvin** [comment]
macos binaries have been being built for some time, binaries are also built for 64 bit windows.

I'll correct the message in the docs. now.
