### ISSUE TITLE
How to use a field called "self"

### ISSUE THREAD

**Issue by skaaptjop** [samuelcolvin/pydantic#629]
# Question
Is it possible to have a field on a model called "self"?
(Background to the question is JSON-API has links called "self", "related" etc.)

* Python version 3.7.3
* Pydantic version 0.29

```py
from pydantic import BaseModel

class Model(BaseModel):
    self: str

m = Model(self="some URL")
# TypeError: __init__() got multiple values for argument 'self'
```

I tried calling the field "self_" using an alias called "self"

```py
from pydantic import BaseModel, Schema

class Model(BaseModel):
    self_: str = Schema(alias="self")

m = Model(self="some URL")
# TypeError: __init__() got multiple values for argument 'self'
```

**Comment by dmontagu** [comment]
Try `m = Model(self_=“some URL”)` with the rest of the code as is

**Comment by skaaptjop** [comment]
@dmontagu the problem is deserialization. 
I get a json body in a request with {"self": "someurl"} in it and I can't create a model instance without preparsing the body to replace "self" with "self_"

If pydantic had a way to "preload" like marshmallow does it might help?

**Comment by samuelcolvin** [comment]
Would #624 help?

**Comment by dmontagu** [comment]
@samuelcolvin would having a load alias give you a different function to call that didn’t already have `self` as a parameter? I don’t see that discussed in the linked issue.

Given how frequently the specific field name `self` seems to be desired (I think it has meaning in certain json schema specs), might it make sense to rename `self` to `__self__` or something else equally unlikely to cause conflicts in `BaseModel.__init__` (and perhaps other methods expecting field names as kwargs)? Unless the approach of calling `Model(**data)` to initialize a model becomes discouraged, it feels unfortunate to me to have to change the model initialization code just to support a reasonably-named field (reasonable in a JSON context, rather than a python context anyway).

**Comment by skaaptjop** [comment]
@samuelcolvin not sure whether splitting out load and dump aliases changes the fact.

Seems to me being able to avoid `Model(**data)` to initialize a model avoids all sorts of possible issues with name clashes. Moving this to a 'marshmallow' style `load(...)` has other advantages for pre-formatting data etc. but I don't really want to suggest any specific approach here not knowing the history and roadmap of the project well enough, rather just if there is a way to handle this.

Regardless, as @dmontagu points out, 'self' and even 'kwargs' should be possible to specify in a schema.

**Comment by samuelcolvin** [comment]
Sorry, I'm back at my computer and looking at this properly now.

This should be possible using `parse_obj` (I guess the equivalent of marshmallow's `load`), however at the moment `parse_obj` calls `__init__` in turn thereby raising the same exception.

Would #632 fix this for you?

**Comment by skaaptjop** [comment]
@samuelcolvin so that would work if 'self' is at the root of the dict but if it's nested it doesn't.
e.g.

```py
from pydantic import BaseModel

class Nested(BaseModel):
    self: str

class Model(BaseModel):
    nested: Nested

m = Model.parse_obj({"nested": {"self": "me"}})
#pydantic.error_wrappers.ValidationError: 1 validation error
#nested
# __init__() got multiple values for argument 'self' (type=type_error)
```

**Comment by samuelcolvin** [comment]
good catch, what about this?

**Comment by skaaptjop** [comment]
That seems to do it. Nice.
Just to recap some of the concepts you've discussed here though:

- we would need to user `parse_obj` in order to pass through field names that might clash.
- this prohibits trying to do this with Model(...) straight.

At the risk of going off original topic, you mention using `parse_obj` as a "loader". Would this imply that we could/should overload it to support custom deserialisation?

**Comment by Lnaden** [comment]
I'd like to possibly re-open this issue and further discuss the validity of this feature within Pydantic. Particularly the fact that `self` has a very well established and understood meaning in the Python world (https://www.python.org/dev/peps/pep-0008/#id46) and loss of the ability to do `Model(**kwargs)` is a very non-Pythonic way of doing things. Also feel free to just shoot this discussion down since Python conventions are only that and not really enforceable.

I worry that defining an attribute within Python classes called `self` will very quickly lead to confusion among Python-centric users. I'm not versed in JSON API at all, but the use case for `self` seems a bit narrow from what I can read (I can't find a use case for `kwargs`, but I would be very interested to see one!). I don't want to discount it entirely, but I wanted to talk about it. I have an implementation in #644 to fix an inheritance bug, but it required me to choose a different arg than `self`. 

Given that Pydantic is not JSON (although it does support interfaces to JSON Schema Core, JSON Schema Validation, and OpenAPI, but not JSON API), I'm not sure of the merits of putting this in because `self` is a neigh hallowed word in the Python world; and it makes me uneasy even in my own implementation. Even an attribute like `self.self` is very rare. I'm happy to discuss options, but I'm not sure I fully agree with this as a base-line feature from a (personal) Python-centric view.

A possible alternate solution would be to make a special Type in Pydantic which can handle this so allowing `self` becomes a special case rather than the base line as I have implemented in #644, although I worry doing so would just make a special `BaseModel` which can have `self` in it serving to create just a derivative of `BaseModel` rather than a simple Type like `datetime`.

Another option would be to have the pre-formatter as suggested above, which maps an arg like `self` to something else until the init is done and then you can have `self.self` internally if you need to, but I don't know how efficient that would be since it effectively adds a special case to all `__init__` calls. But these are implementation details rather than the philosophical details I'm more concerned about.

**Comment by Lnaden** [comment]
I suppose the broader issue here is that the first arg of Python class in its code automatically becomes an unusable keyword arg, and there is no way around that. For example, in #644 I use `pydantic_base_model_init` instead of `self`, which will have the same problem as using `self` did pre-#632 if someone ever tried to use "pydantic_base_model_init" as one of their attributes. So my take is that if we have to have one word blocked out, it may as well be `self` since most Python users will likely be aware of it, or at minimum understand why that particular word is blocked if they try to use it.

**Comment by Lnaden** [comment]
Thinking about this a bit more, I'm being a bit over-zealous about this. My implementation in #644 has the non-self term only showing up in the `init` call, everywhere else the `self` is used, it's a very minor change in the grand scheme of things, and it works. 

There are still the outstanding things of something possibly colliding with `pydantic_base_model_init `, but if that's a concern we can pick some random valid python-variable-name string. Then there is the double edge case where someone inherits and modifies `__init__` + tries to use `self` as the first arg + is trying to use "self" as an attribute (either as the model or inherited) which can all be fixed by "don't use self in the `__init__` as you are already are using it as an attribute"

Shorter: I think I'm actually fine with this, a little uneasy, but its small corner cases and arguing for convention rather than functionality.

**Comment by Lnaden** [comment]
With #644 and my own re-thinking of the issue, I think this can be re-closed. Thanks you!

**Comment by Lnaden** [comment]
@skaaptjop one small thing to note from your recap:

> we would need to user `parse_obj` in order to pass through field names that might clash.
> this prohibits trying to do this with Model(...) straight.

These limitations should not be in place anymore with #644, you ought to be able to just call the model itself now `Model(**input_dict)`, although the `parse_obj(input_dict)` factory still works too. 

There will technically be a crash if anyone tries to use an attribute called `__pydantic_init__`, but that seems even more unlikely than `self`. Limitation of the Python Class constructors, *something* will always be a collision.

**Comment by skaaptjop** [comment]
@Lnaden thanks so much for all your thoughts on this.
I can't help but disagree strongly on not supporting a self argument for pythonic reasons. Pydantic is a serialiser and a deserialiser and as such can't be restrictive in what it allows you to serialise. When used in projects like FastAPI it simply has to support the semantics of whatever API the project is used for. In my specific case that is a JSON-API one and is a great case in point. The chosen means of using the class constructor to achieve this means that it would need to support it.

Now I do agree that trying to force "self" around the python code base is silly and painful at best, there still has to be *some* way in which it can be marshalled in?. Using an alias (e.g. "self_") is fine but then that alias appears in your schema. Marshaling breaks in one direction no matter what.

Limiting the attribute to a namespace tied name (e.g. __pydantic__init__) is not an entirely bad idea since the name is tied to the namespace.

**Comment by uralbash** [comment]
Can I use field called "pass" ?

**Comment by samuelcolvin** [comment]
Your can have a field with an [`alias`](https://pydantic-docs.helpmanual.io/usage/schema/#field-customization) of `pass`
