### ISSUE TITLE
No validation for UUIDs

### ISSUE THREAD

**Issue by thedrow** [samuelcolvin/pydantic#65]
There is not validator for UUIDs.
Can we add one?

**Comment by samuelcolvin** [comment]
Yes, should be very simple. I meant to but hadn't got round to it.

Should be as simple as adding a method [here](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/validators.py#L92). Want to submit a PR?

**Comment by thedrow** [comment]
I'll add it to my todo list :)

**Comment by mgu** [comment]
I tried another solution because I wanted to use strings (input & output). see https://github.com/samuelcolvin/pydantic/compare/master...mgu:add-type-uuidstr
But this also could be done by adding a validator for `uuid.UUID` in `validators.py`.

I don't know what is the best solution

**Comment by samuelcolvin** [comment]
Hi guys, this should be fixed in #89. Would be great if you could review and let me know if this works for you.

@mgu, I understand what you mean by wanting to use strings, but since python has the `UUID` type and  I'm trying where possible to use the python type where it exists I've that. For almost any real life application `UUID(...)` duck types to a string so it shouldn't be a problem.
