### ISSUE TITLE
Support assert statements inside validators

### ISSUE THREAD

**Issue by abdusco** [samuelcolvin/pydantic#654]
# Feature Request

I like how simple and straightforward it is to use `pytest`, which lets you write tests using `assert <expression>`. I wonder if it can be brought into `pydantic` to make validators easier to read and write.

```python
from pydantic import BaseModel, validator
class AModel(BaseModel):
    a_field: str

    @validator('a_field')
    def validate_a_field(cls, v):
        assert 'hello' in v, 'v does not include hello'
```

Currently pydantic supports raising `ValueError` and `TypeError` [0]. Even though this change would be nothing but a syntactic sugar, I think it would be a nice addition to manually raising errors.

I've written the feature, added the tests and updated the docs in this PR:  https://github.com/samuelcolvin/pydantic/pull/653

- [0] https://pydantic-docs.helpmanual.io/#validators

**Comment by samuelcolvin** [comment]
Personally I think this sounds like a great idea, but I have some questions/concerns:
* is it going to break anything I haven't thought of?
* will it be too confusing in pytest/unit tests? I guess people don't have to use them if they don't want to
* do we need to make any changes to exception `types`? eg. is this a `value_error` or should we have a new root type `assertion_error`
* we need to document **clearly** that these checks will cease to be run if python is run with debug false. Anyone actually do that?

**Comment by samuelcolvin** [comment]
let's give it at least a week for people to give feedback.

**Comment by dmontagu** [comment]
The one thing that stands out to me as a potential concern is that, if I understand correctly, assert statements are disabled when running python in "optimized mode", i.e. with the `-O` flag (this is discussed in some depth in this stack overflow answer: https://stackoverflow.com/questions/1273211/disable-assertions-in-python).

I'm not sure how commonly used that flag is (I think most people aren't even aware of the option), but I've always taken it as an indication that assert statements should be used for debugging, and never part of expected error handling (e.g., you generally shouldn't be catching an AssertionError in production code). Since validation errors may be expected during runtime even in production (e.g., if running a webserver that does json payload validation), using assert statements for validation could lead to unexpected behavior.

Presumably if you care about the "-O" flag, you are aware of the issues with asserts and would avoid them in your validators, so this feature would basically just be opt-in; given that, I could see arguments both for and against. But either way it probably should not be recommended without a warning.

(Obviously when using pytest, where I agree that assert statements provide a nice API, this consideration would not apply.)

**Comment by tiangolo** [comment]
I like it! :tada: :rocket: 

And you have very clever concerns/insights in the comments above. I don't have anything else to say :sweat_smile:

**Comment by koxudaxi** [comment]
I vote for this idea 👍 
I think documents can cover some worry when using the feature.

**Comment by samuelcolvin** [comment]
Great, let's do it. PR welcome.

**Comment by abdusco** [comment]
@samuelcolvin https://github.com/samuelcolvin/pydantic/pull/653

**Comment by pawelswiecki** [comment]
#653 is merged so this could be closed, I think.

**Comment by PrettyWood** [comment]
Thanks @pawelswiecki you're right !
