### ISSUE TITLE
Union produces `anyOf` schema

### ISSUE THREAD

**Issue by layday** [samuelcolvin/pydantic#656]
# Bug

```py
In [1]: import sys

In [2]: sys.platform, sys.version
Out[2]:
('darwin',
 '3.7.2 (default, Mar  1 2019, 12:15:59) \n[Clang 5.0.2 (tags/RELEASE_502/final)]')

In [3]: import pydantic

In [4]: pydantic.VERSION
Out[4]: StrictVersion ('0.30')

In [5]: from typing import Union

In [6]: class Foo(pydantic.BaseModel):
   ...:     bar: Union[int, str]

In [7]: Foo.schema()
Out[7]:
{'title': 'Foo',
 'type': 'object',
 'properties': {'bar': {'title': 'Bar',
   'anyOf': [{'type': 'integer'}, {'type': 'string'}]}},
 'required': ['bar']}
```

Unions correspond to a `oneOf` relationship in [JSON Schema](https://json-schema.org/latest/json-schema-validation.html):

> An instance validates successfully against this keyword if it validates successfully against exactly one schema defined by this keyword's value. 

Whereas `anyOf` is described as follows:

> An instance validates successfully against this keyword if it validates successfully against at least one schema defined by this keyword's value.

**Comment by dmontagu** [comment]
Based on [this discussion](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) of the distinction between `oneOf` and `anyOf`, I think the way pydantic currently handles parsing is more in line with `anyOf` than `oneOf`: if an object can be parsed into **any** of the unioned schemas, it will be (in particular, it will be parsed as the first valid choice in the union), even when it could be parsed into multiple.

I would think that in order for it to make sense to use `oneOf` instead of `anyOf`, you'd want to have a validator explicitly checking that it is not valid for multiple schemas. Either way, it would be nice if it were possible to specify (maybe it already is via arguments to `Schema`?).

**Comment by layday** [comment]
I think you are misinterpreting `anyOf`. If you have an

```yaml
anyOf:
  - type: object
    properties:
      foo:
        type: str
  - type: object
    properties:
      bar:
        type: str
```

that means that any of the following are valid:

```yaml
---
foo: 'foo'
---
bar: 'bar'
---
foo: 'foo'
bar: 'bar'
```

This is equivalent to multiple inheritance in Python and it is not a relationship you can describe with a `Union`.  Whether Pydantic will happily coerce an integer to a string is quite besides what you can (are supposed to) encode into a JSON schema.

**Comment by dmontagu** [comment]
@layday 

I think I understand the point you are making, and I think it is reasonable, but there are a few issues that I still think could be problematic:

1) Without a modification to the parsing behavior of `Union`, the schema would not reflect the validation performed (as I described above). In particular, in your example, pydantic would not currently raise a `ValidationError` for `"{'foo': 'foo', 'bar': 'bar'}"` (unless you disable extra values), where I would expect a schema annotated with `oneOf` to raise an error for this input. (But maybe it's not a big deal if the schema and validation are slightly out of sync?)

2) In the example from my link above, they explicitly demonstrate the use of `anyOf` by having a `PetByType` schema and a `PetByAge` schema, and use `anyOf` to accept either schema at the endpoint. This could currently be replicated in pydantic via `Union[PetByType, PetByAge]` (if you created the appropriate `PetByType` and `PetByAge` models). While pydantic may not parse the item precisely the way you'd want (e.g., dropping the age if you provide type), modifying the generated schema `Union` would indicate this is disallowed (when that may not be the intention). I see it as a bigger problem if it is not possible/convenient to create a schema that reflects your intentions.

Related to the previous point, if `Union` always used `oneOf` instead of `anyOf`, **how would you handle the case where one model has a superset of the other's fields**? For example:

```python
class MyModel(BaseModel):
    foo: str

class MyExtendedModel(MyModel):
    bar: str

class MyContainingModel(BaseModel):
    model: Union[MyExtendedModel, MyModel]
```

Currently, pydantic would handle this by parsing first to MyExtendedModel, and then to MyModel (e.g., if `bar` was missing); I would argue this is a useful capability. If the schema specified `oneOf`, I would expect that the extended model should always be rejected (as json valid for the extended model is always valid for the submodel).

Am I misunderstanding something here?

At any rate, I certainly think it would be nice to be able to indicate which version you want in the schema (if this were convenient, I wouldn't care which version was the default). It sounds like @tiangolo has some intention of expanding the schema-specification capabilities (although maybe this modification is already possible using `= Schema`?).

**Comment by layday** [comment]
To forbid extra values in JSON Schema you would need to set `additionalProperties` to false.  A schema annotated with `oneOf` should not raise an error for `"{'foo': 'foo', 'bar': 'bar'}"` in any JSON Schema implementation.

> If the schema specified `oneOf`, I would expect that the extended model should always be rejected (as json valid for the extended model is always valid for the submodel).

JSON Schema does not define how overlapping schemas inside `oneOf` should be handled.  This makes sense when you consider it was designed specifically as a validator and not as some kind of - I don't know - ADT abstraction layer.  The idiomatic way to validate your example in JSON Schema would be:

```yaml
type: object
properties:
  foo:
    type: str
  bar:
    type: str
required:
  - foo
```

**Comment by dmontagu** [comment]
I agree that the schema generated with nested classes is not idiomatic, but given it is being automatically generated I would prioritize validity more highly; I wouldn't necessarily expect pydantic to be able to generate the schema you wrote above automatically directly from the models.

> JSON Schema does not define how overlapping schemas inside oneOf should be handled. 

I read the [json schema documentation](https://json-schema.org/understanding-json-schema/reference/combining.html) on the topic of combining schemas, and while it does not explicitly address the issue of overlapping schemas, given that `additionalProperties` are allowed unless explicitly disallowed, the spec seems unambiguous to me on this point:

> The keywords used to combine schemas are:
>    allOf: Must be valid against *all* of the subschemas
>    anyOf: Must be valid against *any* of the subschemas
>    oneOf: Must be valid against *exactly one* of the subschemas

Without specifying `additionalProperties: False`, it seems clear that `{"model": {"foo": "foo", "bar": "bar"}}` would not be valid for the generated schema if `Union` translated to `oneOf` instead of `anyOf` -- it is clearly valid against **both** of the subschemas, not "exactly one".

This is also consistent with what was described in the [swagger docs](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/):

> The following JSON object is valid against both schemas, so the response body is incorrect – it **should be valid against only one of the schemas, since we are using the oneOf keyword**. 

(emphasis mine).

------

Given pydantic will successfully parse a `Union` field if the provided json object meets *any* of the subschemas (regardless of how many of the subschemas it is valid for, which is the *only* distinction in validity between `anyOf` and `oneOf` as far as I can tell from any documentation/specs I've seen), it seems to me that the default generated schema really *should* use `anyOf` -- otherwise it would be out of sync with what the parsing function would consider valid.

The way I see it, there are three alternatives:
1) `anyOf` becomes `oneOf` in the schemas generated for `Union`, and in some cases models that are invalid for the generated schema will be parsed
2) `anyOf` is replaced in `Union` with `oneOf`, and a validation is added to ensure that the object does *not* parse as any of the other provided schemas
3) Things stay as they are now

I think choice 2 is unrealistic, both for performance and ease-of-use reasons.

My current perspective is that the implementation goal for schema generation should be to come as close as possible to the following:
```
an object is valid for a model's generated schema

    if and only if

pydantic does not raise a ValidationError when `parse_obj` is called on the object
```
From that perspective, changing from `anyOf` to `oneOf` feels like a regression.

Is there a functional capability that changing this would enable?

**Comment by layday** [comment]
I was wrong and agree with everything you've said above.  I will go ahead and close this issue.

**Comment by dnsco** [comment]
Is there any way this could be an option on the field? If I manually change the attribute to oneOf the generated typescript type I get from openApi is (correctly) ```OptionOne | OptionTwo```,  with all of I'm getting ```Partial<OptionOne> & Partial<Option2>```, I think the first definition is an exact translation of the python of the python type, whereas the second definition is potentially more in line with the previously laid out understand of the spec. 

Given that the discriminator having a literal type makes the types non-overlapping, I feel like it's much more useful to be able to access strict discriminated union definition.

My current work around is to ```s/anyOf/oneOf/``` on the schema before running it through the typescript generator, so I guess I'm fine without this feature being added, though I would prefer only having to encode this knowledge into the type system once, rather than using sed to maintain it.

All that said, thanks for the great library!

**Comment by Norbo11** [comment]
I'm in the exact same boat as @dnsco. I'm generating a Typescript client using `openapi-generator` and any variant I try is completely broken when used with `anyOf`. I got around this problem using the `schema_extra` functionality in Pydantic to change the generated `anyOf` into a `oneOf`:

```python
class MyModel(BaseModel):
    something: Union[A, B] = Field(
        ..., discriminator="discriminator_field"
    )

    class Config:
        @staticmethod
        def schema_extra(schema: Dict[str, Any], model: BaseBasketItem) -> None:
            schema["properties"]["core_details"]["oneOf"] = schema["properties"]["core_details"]["anyOf"]
            del schema["properties"]["core_details"]["anyOf"]
```

I understand why Pydantic has translated `Union` types into `anyOf` in the past. However, with the recent introduction of discriminated unions, I am wondering whether they are more accurately translated as `oneOf`, since the incoming schemas should only match exactly one of the Union's members?

**Comment by dnsco** [comment]
@Norbo11 If you happen to be uing fastapi you can post-process your entire generated schema like so:

```Python
from fastapi.openapi.utils import get_openapi

def change_union_serialization(d: Dict[str, Any]):
    if "anyOf" in d:
        d["oneOf"] = d["anyOf"]
        del d["anyOf"]

    for child in d.values():
        if isinstance(child, dict):
            change_union_serialization(child)

    return d


def custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema

    openapi_schema = get_openapi(
        title="Project name",
        version="0.1.0",
        routes=app.routes,
    )

    app.openapi_schema = change_union_serialization(openapi_schema)
    return app.openapi_schema


app.openapi = custom_openapi
```

**Comment by Norbo11** [comment]
@dnsco I am indeed - nice one, will keep this in mind.
