### ISSUE TITLE
No validation on default values?

### ISSUE THREAD

**Issue by timonbimon** [samuelcolvin/pydantic#669]
# Question | Bug
For bugs/questions:
* OS: Mac 
* Python version: 3.7.3
* Pydantic version: 0.30.1

Not sure if this is a question or a bug, actually.

```py
from typing import List

import pydantic
from pydantic import BaseModel

class Foo(BaseModel):
    bar: List[float] = [1, "2"] 
    
Foo()
```
You get `<Foo bar=[1, '2']>`
Whereas when doing
```
Foo(bar=[1, "2"])
```
You get `<Foo bar=[1.0, 2.0]>`

It seems that the validation is not run on default values. I tripped over this in one of my projects and was wondering if this is intended behavior? 

It seems that this behavior can lead to confusion when someone accidentally puts a wrong default value and you trust Pydantic to only return validated values to you.

**Comment by dmontagu** [comment]
I think this is disabled by default for performance reasons; you can enable validation for default values by setting `validate_all = True` in the model config:

```python
class Foo(BaseModel):
    bar: List[float] = [1, "2"]

    class Config:
    	validate_all = True
    
print(Foo())
# <Foo bar=[1.0, 2.0]>
```

If you want to reuse that config setting in many places, you can set it on a base class, then inherit from that base class everywhere and have all your models receive `validate_all = True` in the config without needing to copy the config-setting lines everywhere.

----

For what it's worth, the specific error from your example would have been detected by mypy:
```
error: List item 1 has incompatible type "str"; expected "float"
```
this might help you to catch these sorts of mistakes without being needing to always leave `validate_all = True` (since it will not error in either case, but with `validate_all` on it will result in a different value being present on the model).

**Comment by timonbimon** [comment]
Awesome, thanks a lot, that makes a lot of sense!
