### ISSUE TITLE
How to validate on Instances, not Class

### ISSUE THREAD

**Issue by roykim98** [samuelcolvin/pydantic#749]
# Question

I know that validators are class methods. What if I wanted to validate on an instance? I've combed through the docs and examples and have not been able to find an answer.

Please complete:
* OS: **MacOS Mojave**
* Python version `import sys; print(sys.version)`: **3.7.3**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.32.1**

```
class DateParams(BaseModel):
    begin_date: str
    end_date: str

    def __init__(self, args, max_years={}):
        super().__init__(**args)
        self.max_years = max_years

    def process_years(date, max_years):
        ...

    @validator("begin_date", always=True)
    def begin_date_validator(cls, begin_date):
        begin_date = validate_date_str(begin_date, "begin_date")
        process_years(begin_date, max_years)
        return begin_date

    @validator("end_date", always=True)
    def end_date_validator(cls, end_date):
        end_date = validate_date_str(end_date, "end_date")
        process_years(end_date, max_years)
        return end_date

```
Suppose I have a class such as above, and I wanted to instantiate multiple `DateParams` with different `max_years`, but the same `process_years`. How would I achieve this? This would be easily resolvable if I could call the validators on an instance instead of on the class.

**Comment by dmontagu** [comment]
@roykim98 Probably the easiest thing to do would be to add `max_years` as a field on the model (above the other two), and add another positional argument to the `validator`s -- it will contain the values of the previously-parsed fields. Given you are trying to store it on the object anyway, maybe this is reasonable?

Another option would be to use `pydantic.dataclasses.dataclass`, which has support for `dataclasses.InitVar`, which would allow you to do validation in the `__post_init_post_parse__` (though not in a validator).

Note: if you want to set additional properties which are not fields on the model instance, you'll need to set the `Config` to allow extra.

-----

In general, because of how much pydantic handles transparently, if you want/need to substantially change the API for a model, it's probably worth thinking about if you could achieve the pattern with composition, rather than inheritance. Going "off-road" in subclasses of `BaseModel` like this; is likely to cause confusing and subtle (or not so subtle) errors. In this case, for example, it will be impossible for pydantic to parse any models using `DateParams` as a submodel due to the modification to the `__init__` signature.

**Comment by samuelcolvin** [comment]
You want to do something like 

```py
from datetime import date
from typing import ClassVar

from pydantic import BaseModel, validator

class DateParams(BaseModel):
    max_years: ClassVar[int] = 123
    begin_date: date
    end_date: date

    @classmethod
    def process_years(cls, date):
        print(date, cls.max_years)

    @validator('begin_date', always=True)
    def begin_date_validator(cls, begin_date):
        cls.process_years(begin_date)
        return begin_date

    @validator('end_date', always=True)
    def end_date_validator(cls, end_date):
        cls.process_years(end_date)
        return end_date

DateParams(begin_date='2019-06-01', end_date='2019-06-02')
```

If you want to modify `max_years` you can:
* inherit from `DateParams` and override `max_years`
* remove `ClassVar` and make `max_years` a normal field you set at `__init__(self, max_years=..., ...)`, then use another argument to the validators eg. `values` which will contain `max_years`.
* or even, use [`create_model`](https://pydantic-docs.helpmanual.io/#dynamic-model-creation) to dynamically create models with `__base__=DateParams` and `max_years` modified.

**Comment by roykim98** [comment]
Is there a way to make an abstract attribute in Pydantic? Suppose I wanted to make `max_years`  as a field on the model, but have it be an abstract class property. Is this possible?
