### ISSUE TITLE
sphinx-pydantic: sphinx extension for pydantic schemas

### ISSUE THREAD

**Issue by Zsailer** [samuelcolvin/pydantic#773]
I thought others might find this useful, so posting here. Feel free to close anytime.

We've been exploring pydantic for some subprojects we've been working on @jupyter. In that exploration, I wrote [sphinx-pydantic](https://github.com/Zsailer/sphinx-pydantic)—a sphinx extension for generating schema documentation from pydantic objects.

This makes it easy to generate human-readable documentation for schemas producted by pydantic objects. We're using pydantic and this extension to write+validate JSON schemas and auto-generate user documentation for those schemas.

See a simple example [here](https://sphinx-pydantic.readthedocs.io/en/latest/).

[repo](https://github.com/Zsailer/sphinx-pydantic) | [documentation](https://sphinx-pydantic.readthedocs.io/en/latest/)

**Comment by samuelcolvin** [comment]
Awesome, great to hear you're using pydantic.

Would you consider adding sphinx-pydantic and perhaps any notable subprojects to the [Using Pydantic](https://github.com/samuelcolvin/pydantic/blob/master/docs/index.rst#using-pydantic) section of the docs?

I'll leave this open for a week or two to increase the chance others seeing it.

**Comment by mansenfranzen** [comment]
Since this might be related, I created a sphinx autodoc extension called [`autodoc_pydantic`](https://github.com/mansenfranzen/autodoc_pydantic) that seamlessly integrates with sphinx autodoc to document pydantic models/settings. 

It is different from `sphinx-pydantic` because it renders the generated documentation in standard layout rather than putting the schema into a table. Additionally, it provides default values, alias and constraints for model fields, adds references between validators and corresponding fields and more.

**Comment by mscheltienne** [comment]
Since `autodoc_pydantic` has gone unmaintained (it was my go to extension to document models), here is a replacement using the `sphinx` 9.0+ API (they changed how `autodoc` works - `autodoc_pydantic` is very broken on 9.0+). It's not a 1:1 match in feature/design but it covers most of what `autodoc_pydantic` used to provide: https://pypi.org/project/sphinxcontrib-pydantic/
