### ISSUE TITLE
More complex, practical examples of custom types in the docs

### ISSUE THREAD

**Issue by dmontagu** [samuelcolvin/pydantic#789]
(This issue is a follow-up to the point I made and ensuing discussion in https://github.com/samuelcolvin/pydantic/issues/788; I wanted to open a new issue rather than derailing that one.)

@samuelcolvin
The reason I would like a more sophisticated example like that from #788 in the docs is that, until I had actually worked through writing pull requests for a handful of incrementally more complex types (e.g., Strict/RelaxedBool, Base64Encoded, etc.), I didn't feel like I had a good sense of what it would look like to build a complex, practical type with pydantic. 

Even now, I am rarely inclined to create a custom type in my own code/projects, and would have to think somewhat deeply / reference the docs to implement a type like the one in #788, despite the clean, simple API for doing so.

I currently attribute this to the lack of powerful, practical, domain-specific examples in the documentation.

Most of the examples in the docs perform more general validation (things like string length, etc.). Recalling my perspective as a new user (which wasn't actually that long ago 😅),  the examples in the docs 1) were a little too abstract for my imagination to grasp all of the possibilities, and 2) their simplicity led me to implicitly believe that "proper" usage of the library involved a small number of more lightweight, simple validations. Clearly its capabilities go well beyond that; it just wasn't my first impression.

I think an example like #788 would really help inspire intermediate pydantic users to build and use custom types where appropriate in their projects.

-----

On the other hand, I do understand the desire to show clearly unrealistic types in the "Custom Data Types" section -- better for people to use a shared, maintained implementation, rather than copy/paste. However, I think there may be something to be said for doing more to guide users toward self-sufficiency (going beyond a description of the available APIs).

Sqlalchemy is an example of a project that I think follows this strategy: for example, their [custom type docs](https://docs.sqlalchemy.org/en/13/core/custom_types.html) include a "Backend-agnostic GUID Type". That type *could* be integrated directly into the library, would probably get more usage if it *were* integrated into the library, and there are several stackoverflow answers that essentially recommend copy/pasting it into your project. But I think by including it *only as an example in the docs*, it actually helps push users toward understanding the internals, and becoming self-sufficient in creating their own custom types.

I think a similar "advanced examples" section like that in the pydantic docs would result in fewer pull/feature-requests for custom types, and more users just using the example as a starting point for implementing their own types.

-----

I would be very interested to hear if anyone else has had an experience similar to mine. If I am an outlier, the docs shouldn't be changed just for me!

**Comment by samuelcolvin** [comment]
Thanks, for the question/suggestion. In general I agree with it.

I agree entirely that the docs are not as good as they should be. I can't pretend I'm very good at writing docs (or that I enjoy it like writing code), but I'm still prepared to put some effort into trying to make it as good as possible.

I want to build a new help site with the following intentions:
* make the project more attracting to get started with (fastapi's docs are a good example)
* split the docs into multiple pages so it's not just one long wall of text
* use markdown not rst to make it more attractive to contribute to (I also much prefer writing md to rst)
* properly test examples so they don't go out of date (as much)

That's not required for more/better/more complex examples, but I thought better to mention it now.

-----------------------------------------

Regarding real world examples, I think there should only ever be two types of code in the world:
* code I write, I understand, I own, I maintain, I test, that lives in my version control (where I/my can also mean my team).
* code that someone else is responsible for that does not live in my version control and is only referenced by a name and version number in a requirements file.

**But there's a third type of code:** code I've copied from somewhere on the internet (can I remember where?) that seemed to sort of work so I didn't bother understanding all of it, it doesn't get updated when the original developer or someone else finds a problem with it, my tests for it are naive or non-existent. It's the same reason I don't like cookiecutter/bootstrapping tools. No one feels ownership of this code and **it is demonstrably bad**, but it's all too common.

The problem with doc examples that have a real world usage is that they encourage the third type of code: even if the code in the example is tested (and even has 100% coverage!) when it's first written, what happens if we find a problem with the `luhn` implementation 6 months later? We could release a new version of pydantic with a note telling people who've copied our examples to do so again, yuk.

### So what's the solution?

I would say we should add proper, complex examples to the docs., but always provide a library version of that class and include a prominent notice saying

> don't use this code in production, instead use the production-ready implementation `from pydantic import Whatever` which is fully tested and will receive updates

If we provide a corollary library implementation of all complex real world examples and include a warning like above, I'm happy to include them in the docs.

Does that make sense?

**Comment by drafter250** [comment]
Hi thanks for Pydantic it is a lifesaver! I hope you don't mind my adding my two scents into this conversation... I am in the middle of trying to use pydantic to serialize and de-serialize pandas DataFrames with complex MultiIndexes inside of a larger object structure to and from a json file. I am doing this partly because most of pandas' various save formats don't support MultiIndexes. I am not using it for web but rather for creating a save file for a data-science application.

I have been struggling with the docs because it seems like there are multiple bits and pieces I need to put together to do both serialization & de-serialization. For Example, do I use __post_init___ for custom de-serialization on dataclasses or do I use a custom Json_loader (per v1.0) set in the config class. right now both serialization and de-serialization is included in the "Export Models" Section. I think serialization and de-serialization should each have their own pages, in addition direct comparison to how each is achieved with BaseModel vs dataclasses. Right now I use a BaseModel as the Root object and dataclasses for almost everything else.

**Comment by samuelcolvin** [comment]
This should be fixed by a more advanced and comprehensive example of a custom field type in the docs for #1065. Please comment there if you have any feedback.
