### ISSUE TITLE
No missing attribute error by mypy

### ISSUE THREAD

**Issue by yamitzky** [samuelcolvin/pydantic#95]
mypy does not warn missing attribute when inheriting `BaseModel`.

```python
from pydantic import BaseModel

class A:
    x: int

class B(BaseModel):
    x: int

A().y
B(x=1).y
```

```
main.py:9: error: "A" has no attribute "y"
```

Can I check missing attribute for `B().y`?

**Comment by samuelcolvin** [comment]
Thanks for the question.

I would guess this is because `BaseModel` [implements `__getattr__`](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L104) so mypy can't easily work out whether `B().y` would raise an `AttributeError`. 

Not really much we can do about this I'm afraid.

**Comment by yamitzky** [comment]
I see... Thanks for your reply!
